# 1.Late Interaction Models

## a. COLBERT

In [ ]:
# !pip install -U einops flash_attn
!pip install -U pylate

In [ ]:
from pylate import indexes, models, retrieve
import json
import numpy as np
import os
from tqdm import tqdm
import pickle
import time

In [ ]:
colbert_model = models.ColBERT(
    model_name_or_path="jinaai/jina-colbert-v2",
    query_prefix="[QueryMarker]",
    document_prefix="[DocumentMarker]",
    attend_to_expansion_tokens=True,
    trust_remote_code=True,
)
colbert_model.query_length = 192

In [ ]:
def embed_texts(batch_texts, model,doc_type):
    if doc_type=="query":
      return model.encode(batch_texts,is_query=True)
    else:
      return model.encode(batch_texts,is_query=False)

In [ ]:
def build_colbert_pipeline(
    texts,
    ids,
    model,
    batch_size=32,
    save_path=None
):

    all_embeddings = []
    total_time = 0

    for i in range(0, len(texts), batch_size):

        batch = texts[i:i+batch_size]

        start=time.time()

        emb = embed_texts(
            batch,
            model,
            doc_type="document"
        )

        end=time.time()

        total_time += end-start

        print(
            f"batch {i//batch_size+1} "
            f"time={end-start:.4f}s"
        )

        all_embeddings.extend(emb)


    if save_path:

        os.makedirs(save_path,exist_ok=True)

        with open(
            os.path.join(
                save_path,
                "colbert_embeddings_docs.pkl"
            ),
            "wb"
        ) as f:
            pickle.dump(all_embeddings,f)


        np.save(
            os.path.join(save_path,"doc_ids.npy"),
            ids
        )

    print("Documents:",len(ids))

    return all_embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

colbert_embeddings= build_colbert_pipeline(
    texts=texts,
    ids=ids,
    model=colbert_model,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

In [ ]:
# Embed queries using ColBERT
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"

output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/"

os.makedirs(output_dir, exist_ok=True)

embedding_file = os.path.join(output_dir, "query_embeddings.pkl")
metadata_file = os.path.join(output_dir, "query_metadata.jsonl")
ids_file = os.path.join(output_dir, "query_ids.npy")

query_embeddings = []
query_ids = []

start_time = time.time()

batch_items = []
batch_texts = []

num_queries = 0


with open(metadata_file, "w", encoding="utf-8") as meta_f:

    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)

            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)


            if len(batch_texts) == BATCH_SIZE:

                # ColBERT query embeddings
                embeddings = embed_texts(
                    batch_texts,
                    colbert_model,
                    doc_type="query"
                )

                for it, emb in zip(batch_items, embeddings):

                    query_embeddings.append(emb)

                    query_ids.append(it["query_id"])


                    metadata = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "gold": it["relevant_subarticles"]
                    }

                    meta_f.write(
                        json.dumps(
                            metadata,
                            ensure_ascii=False
                        ) + "\n"
                    )

                    num_queries += 1


                batch_items = []
                batch_texts = []


        # Remaining batch
        if batch_texts:

            embeddings = embed_texts(
                    batch_texts,
                    colbert_model,
                    doc_type="query"
                )


            for it, emb in zip(batch_items, embeddings):

                query_embeddings.append(emb)

                query_ids.append(it["query_id"])


                metadata = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "gold": it["relevant_subarticles"]
                }

                meta_f.write(
                    json.dumps(
                        metadata,
                        ensure_ascii=False
                    ) + "\n"
                )

                num_queries += 1




end_time = time.time()


# Save token embeddings
with open(embedding_file, "wb") as f:
    pickle.dump(query_embeddings, f)

# Save query IDs
np.save(ids_file, np.array(query_ids))

total_time = end_time - start_time


print("\n================ QUERY EMBEDDING STATS ================")
print(f"Total queries embedded : {num_queries}")
print(f"Total embedding time   : {total_time:.2f} sec")
print(f"Average time/query     : {total_time/num_queries:.6f} sec")

print("Embedding example shape:")
print(query_embeddings[0].shape)

print("========================================================")

Embedding queries: 5731it [05:39, 16.86it/s]

================ QUERY EMBEDDING STATS ================
Total queries embedded : 5731
Total embedding time   : 346.66 sec
Average time/query     : 0.060489 sec
Embedding example shape:
(192, 128)
========================================================

In [ ]:
document_embedding_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/colbert_embeddings_docs.pkl"
documents_ids_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/doc_ids.npy"

# Load document embeddings
with open(document_embedding_file, "rb") as f:
    documents_embeddings = pickle.load(f)

# Load document IDs
documents_ids = np.load(documents_ids_file)

In [ ]:
index = indexes.PLAID(
    index_folder="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/pylate_index_document",
    index_name="index",
    override=True,
)
retriever = retrieve.ColBERT(index=index)

In [ ]:
import time

start_time = time.time()

index.add_documents(
    documents_ids=documents_ids,
    documents_embeddings=documents_embeddings
)

total_time = time.time() - start_time

print(f"Total indexing time: {total_time:.2f}s")

Total indexing time: 773.11s

In [ ]:
#run experiments
query_embedding_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/query_embeddings.pkl"
query_ids_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/query_ids.npy"
metadata_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/query_metadata.jsonl"


#  LOAD QUERY EMBEDDINGS

with open(query_embedding_file, "rb") as f:
    query_embeddings = pickle.load(f)

query_ids = np.load(query_ids_file)


#  LOAD QUERY METADATA

query_metadata = []

with open(metadata_file, "r", encoding="utf-8") as f:
    for line in f:
        query_metadata.append(json.loads(line))


gold_labels = [
    x["gold"] for x in query_metadata
]

print("Queries:", len(query_embeddings))
print("Example query shape:", query_embeddings[0].shape)

# ---------------- RETRIEVAL ----------------
top_k = 100
batch_size = 128


all_results_for_metrics = []


start_time = time.time()


for i in tqdm(
    range(0, len(query_embeddings), batch_size),
    desc="Retrieving"
):

    batch_embeddings = query_embeddings[i:i+batch_size]

    # Batch retrieval
    results = retriever.retrieve(
        queries_embeddings=batch_embeddings,
        k=top_k
    )
    for j, query_results in enumerate(results):

        retrieved_ids = [
            r["id"] for r in query_results
        ]

        all_results_for_metrics.append(
            (
                retrieved_ids,
                gold_labels[i+j]
            )
        )


end_time = time.time()


# -------- STATS --------

retrieval_time = end_time - start_time
num_queries = len(query_embeddings)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries        : {num_queries}")
print(f"Total retrieval time : {retrieval_time:.4f} sec")
print(f"Avg time/query       : {retrieval_time/num_queries:.6f} sec")
print(f"Throughput           : {num_queries/retrieval_time:.2f} queries/sec")
print("=================================================")

Queries: 5731
Example query shape: (192, 128)

Retrieving: 100%|██████████| 45/45 [14:48<00:00, 19.75s/it]

================ RETRIEVAL STATS ================
Total queries        : 5731
Total retrieval time : 888.7068 sec
Avg time/query       : 0.155070 sec
Throughput           : 6.45 queries/sec
=================================================

### Efficiency

In [ ]:
#final indexing time computation
# Warmup
_ = embed_texts(
    texts[:BATCH_SIZE],
    colbert_model,
    doc_type="document"
)


# Measure indexing only
start_time = time.perf_counter()

colbert_embeddings = build_colbert_pipeline(
    texts=texts,
    ids=ids,
    model=colbert_model,
    batch_size=BATCH_SIZE,
    save_path=None   # exclude disk writing
)

end_time = time.perf_counter()


indexing_time = end_time - start_time

avg_time_per_doc = indexing_time / num_docs
throughput = num_docs / indexing_time


print("\n============== INDEXING STATS ==============")
print(f"Documents embedded : {num_docs}")
print(f"Indexing time      : {indexing_time:.2f} sec")
print(f"Time per document  : {avg_time_per_doc:.6f} sec")
print(f"Throughput         : {throughput:.2f} docs/sec")
print("============================================")

In [ ]:
from tqdm import tqdm
import time
import numpy as np

##retrieval check
def measure_search_time(query_embeddings, retriever, top_k=100, batch_size=128):

    # warm-up
    _ = retriever.retrieve(
        queries_embeddings=query_embeddings[:batch_size],
        k=top_k
    )

    times = []

    for run in range(3):

        start = time.perf_counter()

        for i in tqdm(
            range(0, len(query_embeddings), batch_size),
            desc=f"Search run {run+1}/3"
        ):

            batch_embeddings = query_embeddings[i:i+batch_size]

            _ = retriever.retrieve(
                queries_embeddings=batch_embeddings,
                k=top_k
            )

        end = time.perf_counter()

        times.append(end-start)

    return times,np.mean(times), np.std(times)

times,mean_time, std_time = measure_search_time(
    query_embeddings,
    retriever,
    top_k=100,
    batch_size=128
)

print(f"Times={times}")
print(f"Search time: {mean_time:.2f} ± {std_time:.2f} sec")
print(f"Avg/query: {mean_time/len(query_embeddings):.6f} sec")

Search run 1/3:  17%|█▋        | 8/47 [02:25<11:45, 18.08s/it]

In [ ]:
import os

def get_directory_size(folder_path):
    total_size = 0

    for root, _, files in os.walk(folder_path):
        for file in files:
            file_path = os.path.join(root, file)
            total_size += os.path.getsize(file_path)

    size_mb = total_size / (1024 ** 2)
    size_gb = total_size / (1024 ** 3)

    print(f"Folder: {os.path.basename(folder_path)}")
    print(f"Index size: {size_mb:.2f} MB")
    print(f"Index size: {size_gb:.3f} GB")

    return size_gb


index_folder = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/colbert-jina/pylate_index_document"

colbert_index_size = get_directory_size(index_folder)

Folder: pylate_index_document
Index size: 324.96 MB
Index size: 0.317 GB

### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.2256  0.0824     NaN      NaN
1   10  0.2706  0.0548  0.1823   0.1975
2  100  0.4141  0.0094     NaN      NaN

# 2.Dense Embeddings

## Monolingual

### a. Universalml/Nepali Embedding Model

In [ ]:
!pip install faiss-gpu

Requirement already satisfied: faiss-gpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (26.2)
Requirement already satisfied: nvidia-cuda-runtime-cu12<13,>=12.6 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (12.8.90)
Requirement already satisfied: nvidia-cublas-cu12<13,>=12.6 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (12.8.4.1)
Requirement already satisfied: nvidia-curand-cu12<11,>=10.3.7 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (10.3.9.90)

In [ ]:
import os
import json
import numpy as np
import time
import faiss
from tqdm import tqdm

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("universalml/Nepali_Embedding_Model")

In [ ]:
def embed_texts(batch_texts, model):
    return model.encode(batch_texts)

In [ ]:
def build_faiss_pipeline(
    texts,
    ids,
    model,
    batch_size=32,
    save_path=None
):
    all_embeddings = []
    total_time = 0.0
    index=None
    embeddings=None

    for i in tqdm(range(0, len(texts), batch_size)):
        batch = texts[i:i+batch_size]

        start = time.time()

        emb = embed_texts(batch, model)

        end = time.time()
        total_time += (end - start)

        print(f"batch {i//batch_size + 1} | size={len(batch)} | time={end-start:.4f}s")

        all_embeddings.append(emb)


    # --- SAVE ARTIFACTS ---
    if save_path:
        embeddings = np.concatenate(all_embeddings, axis=0).astype("float32")
        dim = np.array(embeddings).shape[1]
        index = faiss.IndexFlatIP(dim)
        index = faiss.IndexIDMap(index)
        index.add_with_ids(embeddings, ids)

        os.makedirs(save_path, exist_ok=True)

        # 1. save faiss index
        faiss.write_index(index, os.path.join(save_path, "sa_faiss.index"))

        # 2. save embeddings
        np.save(os.path.join(save_path, "sa_embeddings.npy"), embeddings)

    print("\n--- summary ---")
    print(f"total embedding time: {total_time:.2f}s")
    print(f"total docs: {len(ids)}")
    print(f"dimension: {dim}")

    return index,embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

index, embeddings = build_faiss_pipeline(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

In [ ]:
#embed queries
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/queries_embed.jsonl"

os.makedirs(os.path.dirname(query_output_file), exist_ok=True)

batch_items = []
batch_texts = []

start_time = time.time()

with open(query_output_file, "w", encoding="utf-8") as out_f:
    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)
            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)

            # ---- RUN BATCH ----
            if len(batch_texts) == BATCH_SIZE:

                embeddings = embed_texts(batch_texts, model)

                for it, emb in zip(batch_items, embeddings):
                    to_write = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "embedding": emb.tolist(),
                        "gold": it["relevant_subarticles"]
                    }
                    out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

                batch_items = []
                batch_texts = []

        # ---- FLUSH REMAINING ----
        if batch_texts:
            embeddings = embed_texts(batch_texts, model)

            for it, emb in zip(batch_items, embeddings):
                to_write = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "embedding": emb.tolist(),
                    "gold": it["relevant_subarticles"]
                }
                out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

end_time = time.time()   # END TIMER

print("Done! Query embeddings written to:", query_output_file)

# FINAL STATS
total_time = end_time - start_time
print(f"\nTotal embedding time: {total_time:.2f} seconds")
print(f"Average time per query: {total_time / sum(1 for _ in open(query_file)):.4f} sec")

Embedding queries: 5731it [06:34, 14.54it/s]

Done! Query embeddings written to: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/queries_embed.jsonl

Total embedding time: 401.03 seconds
Average time per query: 0.0700 sec

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))

query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/queries_embed.jsonl"

all_query_embeddings = []
all_gold_labels = []

print(f"Loading all embeddings from: {query_output_file}")

with open(query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        all_query_embeddings.append(item["embedding"])
        all_gold_labels.append(item["gold"])

# Convert to numpy matrix
query_matrix = np.array(all_query_embeddings).astype("float32")

print(f"Performing batch search for {len(query_matrix)} queries...")

# START TIMER (RETRIEVAL TIME ONLY)
start_time = time.time()

D, I = index.search(query_matrix, 100)

end_time = time.time()

# RETRIEVAL TIME METRICS
retrieval_time = end_time - start_time
num_queries = len(query_matrix)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries           : {num_queries}")
print(f"Total retrieval time    : {retrieval_time:.4f} sec")
print(f"Avg time per query      : {retrieval_time / num_queries:.6f} sec")
print(f"Throughput             : {num_queries / retrieval_time:.2f} queries/sec")
print("=================================================\n")

# FORMAT RESULTS FOR EVALUATION
all_results_for_metrics = []

for row_idx in range(len(I)):
    retrieved_ids = I[row_idx].tolist()
    all_results_for_metrics.append((retrieved_ids, all_gold_labels[row_idx]))

print("Batch retrieval complete.")

#### Efficiency

In [ ]:
def measure_indexing_time(
    texts,
    ids,
    model,
    batch_size,
    save_path="/content/",
    runs=3
):
    """
    Measure dense indexing time over multiple runs.
    """

    num_docs = len(texts)

    # Warmup
    _ = embed_texts(
        texts[:min(batch_size, num_docs)],
        model
    )

    times = []

    for run in range(runs):
        print(f"\nRunning indexing experiment {run+1}/{runs}...")

        start_time = time.perf_counter()

        index, embeddings = build_faiss_pipeline(
            texts=texts,
            ids=ids,
            model=model,
            batch_size=batch_size,
            save_path=save_path
        )

        end_time = time.perf_counter()

        elapsed = end_time - start_time
        times.append(elapsed)

        print(f"Run {run+1} time: {elapsed:.2f} sec")


    avg_indexing_time = np.mean(times)

    results = {
        "num_documents": num_docs,
        "runs": runs,
        "all_times": times,
        "avg_indexing_time_sec": avg_indexing_time,
        "avg_time_per_document_sec": avg_indexing_time / num_docs,
        "throughput_docs_per_sec": num_docs / avg_indexing_time
    }

    return results

indexing_stats = measure_indexing_time(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path="/content/",
    runs=3
)

print("\n============== INDEXING STATS ==============")
print(f"Documents embedded      : {indexing_stats['num_documents']}")
print(f"Runs                    : {indexing_stats['runs']}")
print(f"Individual times        : {indexing_stats['all_times']}")
print(f"Average indexing time   : {indexing_stats['avg_indexing_time_sec']:.2f} sec")
print(f"Avg time per document   : {indexing_stats['avg_time_per_document_sec']:.6f} sec")
print(f"Throughput              : {indexing_stats['throughput_docs_per_sec']:.2f} docs/sec")
print("============================================")

In [ ]:
import time
import numpy as np


def measure_dense_retrieval_latency(
    index,
    queries,
    embedding_model,
    top_k=100,
    warmup=True,
    runs=3
):
    """
    Measure end-to-end dense retrieval latency:
    text query -> embedding -> FAISS search
    """

    num_queries = len(queries)

    # Warm-up
    if warmup:
        emb = embedding_model.encode(
            [queries[0]],
            convert_to_numpy=True
        ).astype("float32")

        index.search(emb, top_k)

    times = []

    for _ in tqdm(range(runs)):

        start = time.perf_counter()

        for query in queries:

            # Query embedding
            query_embedding = embedding_model.encode(
                [query],
                convert_to_numpy=True
            ).astype("float32")

            # Retrieval
            index.search(query_embedding, top_k)

        end = time.perf_counter()

        times.append(end - start)


    avg_time = np.mean(times)

    return {
        "num_queries": num_queries,
        "top_k": top_k,
        "runs": runs,
        "total_time_sec": avg_time,
        "avg_latency_per_query_ms": (avg_time / num_queries) * 1000,
        "queries_per_second": num_queries / avg_time,
        "all_runs": times
    }


#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=3
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/universalml-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=3
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

100%|██████████| 3/3 [22:10<00:00, 443.42s/it]

============== RETRIEVAL STATS ==============
Total queries           : 5731
Top-k                   : 100
Runs                    : 3
Total time              : 443.41 sec
Avg latency per query   : 77.37 ms
Throughput              : 12.92 queries/sec
============================================

#### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })
    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.2603  0.0903     NaN      NaN
1   10  0.3075  0.0601  0.1939   0.2107
2  100  0.4682  0.0106     NaN      NaN

### b. premmm/nepali-embedder-v1

In [ ]:
import warnings
warnings.filterwarnings("ignore")
!pip install --upgrade sentence-transformers

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("premmm/nepali-embedder-v1")

In [ ]:
def embed_texts(batch_texts, model):
    """
    BGE-M3 HF embedding (dense only)
    """
    return model.encode(batch_texts)

In [ ]:
def build_faiss_pipeline(
    texts,
    ids,
    model,
    batch_size=32,
    save_path=None
):
    all_embeddings = []
    total_time = 0.0

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        start = time.time()

        emb = embed_texts(batch, model)

        end = time.time()
        total_time += (end - start)

        print(f"batch {i//batch_size + 1} | size={len(batch)} | time={end-start:.4f}s")

        all_embeddings.append(emb)

    embeddings = np.concatenate(all_embeddings, axis=0).astype("float32")

    dim = np.array(embeddings).shape[1]
    index = faiss.IndexFlatIP(dim)
    index = faiss.IndexIDMap(index)
    index.add_with_ids(embeddings, ids)

    # --- SAVE ARTIFACTS ---
    if save_path:
        os.makedirs(save_path, exist_ok=True)

        # 1. save faiss index
        faiss.write_index(index, os.path.join(save_path, "sa_faiss.index"))

        # 2. save embeddings
        np.save(os.path.join(save_path, "sa_embeddings.npy"), embeddings)

    print("\n--- summary ---")
    print(f"total embedding time: {total_time:.2f}s")
    print(f"total docs: {len(ids)}")
    print(f"dimension: {dim}")

    return index,embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

index, embeddings = build_faiss_pipeline(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

In [ ]:
#embed queries
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/queries_embed.jsonl"

os.makedirs(os.path.dirname(query_output_file), exist_ok=True)

batch_items = []
batch_texts = []

start_time = time.time()   #

with open(query_output_file, "w", encoding="utf-8") as out_f:
    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)
            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)

            # ---- RUN BATCH ----
            if len(batch_texts) == BATCH_SIZE:

                embeddings = embed_texts(batch_texts, model)

                for it, emb in zip(batch_items, embeddings):
                    to_write = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "embedding": emb.tolist(),
                        "gold": it["relevant_subarticles"]
                    }
                    out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

                batch_items = []
                batch_texts = []

        # ---- FLUSH REMAINING ----
        if batch_texts:
            embeddings = embed_texts(batch_texts, model)

            for it, emb in zip(batch_items, embeddings):
                to_write = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "embedding": emb.tolist(),
                    "gold": it["relevant_subarticles"]
                }
                out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

end_time = time.time()   # END TIMER

print("Done! Query embeddings written to:", query_output_file)

# FINAL STATS
total_time = end_time - start_time
print(f"\nTotal embedding time: {total_time:.2f} seconds")
print(f"Average time per query: {total_time / sum(1 for _ in open(query_file)):.4f} sec")

Embedding queries: 5731it [01:26, 66.55it/s]

Done! Query embeddings written to: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/queries_embed.jsonl

Total embedding time: 87.78 seconds
Average time per query: 0.0153 sec

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/queries_embed.jsonl"

all_query_embeddings = []
all_gold_labels = []

print(f"Loading all embeddings from: {query_output_file}")

with open(query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        all_query_embeddings.append(item["embedding"])
        all_gold_labels.append(item["gold"])

# Convert to numpy matrix
query_matrix = np.array(all_query_embeddings).astype("float32")

print(f"Performing batch search for {len(query_matrix)} queries...")

# START TIMER (RETRIEVAL TIME ONLY)
start_time = time.time()

D, I = index.search(query_matrix, 100)

end_time = time.time()

# RETRIEVAL TIME METRICS
retrieval_time = end_time - start_time
num_queries = len(query_matrix)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries           : {num_queries}")
print(f"Total retrieval time    : {retrieval_time:.4f} sec")
print(f"Avg time per query      : {retrieval_time / num_queries:.6f} sec")
print(f"Throughput             : {num_queries / retrieval_time:.2f} queries/sec")
print("=================================================\n")

# FORMAT RESULTS FOR EVALUATION
all_results_for_metrics = []

for row_idx in range(len(I)):
    retrieved_ids = I[row_idx].tolist()
    all_results_for_metrics.append((retrieved_ids, all_gold_labels[row_idx]))

print("Batch retrieval complete.")

Loading all embeddings from: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/queries_embed.jsonl
Performing batch search for 5731 queries...

================ RETRIEVAL STATS ================
Total queries           : 5731
Total retrieval time    : 2.0332 sec
Avg time per query      : 0.000355 sec
Throughput             : 2818.64 queries/sec
=================================================

Batch retrieval complete.

#### Efficiency

In [ ]:
def measure_indexing_time(
    texts,
    ids,
    model,
    batch_size,
    save_path="/content/",
    runs=3
):
    """
    Measure dense indexing time over multiple runs.
    """

    num_docs = len(texts)

    # Warmup
    _ = embed_texts(
        texts[:min(batch_size, num_docs)],
        model
    )

    times = []

    for run in range(runs):
        print(f"\nRunning indexing experiment {run+1}/{runs}...")

        start_time = time.perf_counter()

        index, embeddings = build_faiss_pipeline(
            texts=texts,
            ids=ids,
            model=model,
            batch_size=batch_size,
            save_path=save_path
        )

        end_time = time.perf_counter()

        elapsed = end_time - start_time
        times.append(elapsed)

        print(f"Run {run+1} time: {elapsed:.2f} sec")


    avg_indexing_time = np.mean(times)

    results = {
        "num_documents": num_docs,
        "runs": runs,
        "all_times": times,
        "avg_indexing_time_sec": avg_indexing_time,
        "avg_time_per_document_sec": avg_indexing_time / num_docs,
        "throughput_docs_per_sec": num_docs / avg_indexing_time
    }

    return results

indexing_stats = measure_indexing_time(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path="/content/",
    runs=3
)

print("\n============== INDEXING STATS ==============")
print(f"Documents embedded      : {indexing_stats['num_documents']}")
print(f"Runs                    : {indexing_stats['runs']}")
print(f"Individual times        : {indexing_stats['all_times']}")
print(f"Average indexing time   : {indexing_stats['avg_indexing_time_sec']:.2f} sec")
print(f"Avg time per document   : {indexing_stats['avg_time_per_document_sec']:.6f} sec")
print(f"Throughput              : {indexing_stats['throughput_docs_per_sec']:.2f} docs/sec")
print("============================================")

In [ ]:
import time
import numpy as np
import pandas as pd


def measure_dense_retrieval_latency(
    index,
    queries,
    embedding_model,
    top_k=100,
    warmup=True,
    runs=3
):
    """
    Measure end-to-end dense retrieval latency:
    text query -> embedding -> FAISS search
    """

    num_queries = len(queries)

    # Warm-up
    if warmup:
        emb = embedding_model.encode(
            [queries[0]],
            convert_to_numpy=True
        ).astype("float32")

        index.search(emb, top_k)

    times = []

    for _ in tqdm(range(runs)):

        start = time.perf_counter()

        for query in queries:

            # Query embedding
            query_embedding = embedding_model.encode(
                [query],
                convert_to_numpy=True
            ).astype("float32")

            # Retrieval
            index.search(query_embedding, top_k)

        end = time.perf_counter()

        times.append(end - start)

    avg_time = np.mean(times)

    return {
        "num_queries": num_queries,
        "top_k": top_k,
        "runs": runs,
        "total_time_sec": avg_time,
        "avg_latency_per_query_ms": (avg_time / num_queries) * 1000,
        "queries_per_second": num_queries / avg_time,
        "all_runs": times
    }


#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=3
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

100%|██████████| 3/3 [07:17<00:00, 145.95s/it]

============== RETRIEVAL STATS ==============
Total queries           : 5731
Top-k                   : 100
Runs                    : 3
Total time              : 145.95 sec
Avg latency per query   : 25.47 ms
Throughput              : 39.27 queries/sec
============================================

In [ ]:
import os

def get_index_size(index_path):
    """
    Returns FAISS index size in MB/GB.
    """
    size_bytes = os.path.getsize(index_path)

    return {
        "size_bytes": size_bytes,
        "size_MB": size_bytes / (1024 ** 2),
        "size_GB": size_bytes / (1024 ** 3)
    }

index_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/prem-nepali/sa_faiss.index"

index_size = get_index_size(index_file)

print(f"Index size: {index_size['size_MB']:.2f} MB")
print(f"Index size: {index_size['size_GB']:.3f} GB")

Index size: 65.58 MB
Index size: 0.064 GB

#### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.0955  0.0350     NaN      NaN
1   10  0.1271  0.0261  0.0702    0.082
2  100  0.2750  0.0063     NaN      NaN

### c. acostillio/SemantiSearchNepaliSbert

In [ ]:
!pip install faiss-gpu

In [ ]:

import numpy as np
import pandas as pd
import faiss
import os
import torch
from transformers import AutoTokenizer, AutoModel
import time
import json
from tqdm import tqdm
import torch.nn.functional as F

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("acostillio/SemantiSearchNepaliSbert")

In [ ]:
sum(p.numel() for p in model.parameters())

237556224

In [ ]:
def embed_texts(batch_texts, model):
    return model.encode(batch_texts)

In [ ]:
def build_faiss_pipeline(
    texts,
    ids,
    model,
    batch_size=32,
    save_path=None
):
    all_embeddings = []
    total_time = 0.0

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        start = time.time()

        emb = embed_texts(batch, model)

        end = time.time()
        total_time += (end - start)

        print(f"batch {i//batch_size + 1} | size={len(batch)} | time={end-start:.4f}s")

        all_embeddings.append(emb)

    embeddings = np.concatenate(all_embeddings, axis=0).astype("float32")

    dim = np.array(embeddings).shape[1]
    index = faiss.IndexFlatIP(dim)
    index = faiss.IndexIDMap(index)
    index.add_with_ids(embeddings, ids)

    # --- SAVE ARTIFACTS ---
    if save_path:
        os.makedirs(save_path, exist_ok=True)

        # 1. save faiss index
        faiss.write_index(index, os.path.join(save_path, "sa_faiss.index"))

        # 2. save embeddings
        np.save(os.path.join(save_path, "sa_embeddings.npy"), embeddings)

    print("\n--- summary ---")
    print(f"total embedding time: {total_time:.2f}s")
    print(f"total docs: {len(ids)}")
    print(f"dimension: {dim}")

    return index,embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

index, embeddings = build_faiss_pipeline(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

Loading documents...
Total documents: 22326
batch 1 | size=128 | time=0.2266s
batch 2 | size=128 | time=0.2234s
batch 3 | size=128 | time=0.2373s
batch 4 | size=128 | time=0.2772s
batch 5 | size=128 | time=0.2582s
batch 6 | size=128 | time=0.2829s
batch 7 | size=128 | time=0.2690s
batch 8 | size=128 | time=0.2580s
batch 9 | size=128 | time=0.2901s
batch 10 | size=128 | time=0.2852s
batch 11 | size=128 | time=0.3042s
batch 12 | size=128 | time=0.3066s
batch 13 | size=128 | time=0.3275s
batch 14 | size=128 | time=0.3325s
batch 15 | size=128 | time=0.3419s
batch 16 | size=128 | time=0.3131s
batch 17 | size=128 | time=0.3280s
batch 18 | size=128 | time=0.3394s
batch 19 | size=128 | time=0.3482s
batch 20 | size=128 | time=0.3581s
batch 21 | size=128 | time=0.3584s
batch 22 | size=128 | time=0.3621s
batch 23 | size=128 | time=0.3717s
batch 24 | size=128 | time=0.3862s
batch 25 | size=128 | time=0.3760s
batch 26 | size=128 | time=0.3846s
batch 27 | size=128 | time=0.3911s
batch 28 | size=128 | time=0.4074s
batch 29 | size=128 | time=0.3789s
batch 30 | size=128 | time=0.4002s
batch 31 | size=128 | time=0.3896s
batch 32 | size=128 | time=0.4077s
batch 33 | size=128 | time=0.4059s
batch 34 | size=128 | time=0.4263s
batch 35 | size=128 | time=0.4030s
batch 36 | size=128 | time=0.4117s
batch 37 | size=128 | time=0.4104s
batch 38 | size=128 | time=0.4409s
batch 39 | size=128 | time=0.4416s
batch 40 | size=128 | time=0.4491s
batch 41 | size=128 | time=0.4696s
batch 42 | size=128 | time=0.4654s
batch 43 | size=128 | time=0.4242s
batch 44 | size=128 | time=0.4973s
batch 45 | size=128 | time=0.4846s
batch 46 | size=128 | time=0.5234s
batch 47 | size=128 | time=0.4731s
batch 48 | size=128 | time=0.5041s
batch 49 | size=128 | time=0.5350s
batch 50 | size=128 | time=0.5369s
batch 51 | size=128 | time=0.5654s
batch 52 | size=128 | time=0.5725s
batch 53 | size=128 | time=0.5236s
batch 54 | size=128 | time=0.5581s
batch 55 | size=128 | time=0.5219s
batch 56 | size=128 | time=0.5339s
batch 57 | size=128 | time=0.6085s
batch 58 | size=128 | time=0.6279s
batch 59 | size=128 | time=0.6207s
batch 60 | size=128 | time=0.6803s
batch 61 | size=128 | time=0.6238s
batch 62 | size=128 | time=0.6020s
batch 63 | size=128 | time=0.6611s
batch 64 | size=128 | time=0.6422s
batch 65 | size=128 | time=0.6680s
batch 66 | size=128 | time=0.6960s
batch 67 | size=128 | time=0.6810s
batch 68 | size=128 | time=0.7496s
batch 69 | size=128 | time=0.6532s
batch 70 | size=128 | time=0.7183s
batch 71 | size=128 | time=0.8143s
batch 72 | size=128 | time=0.8079s
batch 73 | size=128 | time=0.8185s
batch 74 | size=128 | time=0.7544s
batch 75 | size=128 | time=0.7256s
batch 76 | size=128 | time=0.6949s
batch 77 | size=128 | time=0.7025s
batch 78 | size=128 | time=0.7488s
batch 79 | size=128 | time=0.7484s
batch 80 | size=128 | time=0.6856s
batch 81 | size=128 | time=0.6980s
batch 82 | size=128 | time=0.7167s
batch 83 | size=128 | time=0.6721s
batch 84 | size=128 | time=0.6559s
batch 85 | size=128 | time=0.7021s
batch 86 | size=128 | time=0.6796s
batch 87 | size=128 | time=0.7800s
batch 88 | size=128 | time=0.7177s
batch 89 | size=128 | time=0.7523s
batch 90 | size=128 | time=0.7720s
batch 91 | size=128 | time=0.8151s
batch 92 | size=128 | time=0.7929s
batch 93 | size=128 | time=0.8113s
batch 94 | size=128 | time=0.7907s
batch 95 | size=128 | time=0.7580s
batch 96 | size=128 | time=0.7717s
batch 97 | size=128 | time=0.8808s
batch 98 | size=128 | time=0.7854s
batch 99 | size=128 | time=0.8014s
batch 100 | size=128 | time=0.8091s
batch 101 | size=128 | time=0.7672s
batch 102 | size=128 | time=0.8072s
batch 103 | size=128 | time=0.8272s
batch 104 | size=128 | time=0.8042s
batch 105 | size=128 | time=0.8553s
batch 106 | size=128 | time=0.7646s
batch 107 | size=128 | time=0.8300s
batch 108 | size=128 | time=0.8353s
batch 109 | size=128 | time=0.8381s
batch 110 | size=128 | time=0.8277s
batch 111 | size=128 | time=0.8893s
batch 112 | size=128 | time=0.9340s
batch 113 | size=128 | time=0.9444s
batch 114 | size=128 | time=0.8920s
batch 115 | size=128 | time=0.8712s
batch 116 | size=128 | time=0.9183s
batch 117 | size=128 | time=0.9843s
batch 118 | size=128 | time=0.8962s
batch 119 | size=128 | time=0.9352s
batch 120 | size=128 | time=1.0001s
batch 121 | size=128 | time=1.0483s
batch 122 | size=128 | time=1.1716s
batch 123 | size=128 | time=0.9995s
batch 124 | size=128 | time=1.0618s
batch 125 | size=128 | time=1.1161s
batch 126 | size=128 | time=1.0535s
batch 127 | size=128 | time=1.2255s
batch 128 | size=128 | time=1.2284s
batch 129 | size=128 | time=1.1148s
batch 130 | size=128 | time=1.3398s
batch 131 | size=128 | time=1.2272s
batch 132 | size=128 | time=1.3515s
batch 133 | size=128 | time=1.4673s
batch 134 | size=128 | time=1.4369s
batch 135 | size=128 | time=1.3490s
batch 136 | size=128 | time=1.3231s
batch 137 | size=128 | time=1.4852s
batch 138 | size=128 | time=1.4370s
batch 139 | size=128 | time=1.5765s
batch 140 | size=128 | time=1.6382s
batch 141 | size=128 | time=1.6483s
batch 142 | size=128 | time=1.8111s
batch 143 | size=128 | time=1.8594s
batch 144 | size=128 | time=1.8039s
batch 145 | size=128 | time=1.7742s
batch 146 | size=128 | time=1.8663s
batch 147 | size=128 | time=1.8631s
batch 148 | size=128 | time=1.8465s
batch 149 | size=128 | time=1.9337s
batch 150 | size=128 | time=1.8888s
batch 151 | size=128 | time=1.9797s
batch 152 | size=128 | time=1.8324s
batch 153 | size=128 | time=1.8382s
batch 154 | size=128 | time=1.9075s
batch 155 | size=128 | time=1.9885s
batch 156 | size=128 | time=2.0495s
batch 157 | size=128 | time=2.2223s
batch 158 | size=128 | time=2.2647s
batch 159 | size=128 | time=2.1117s
batch 160 | size=128 | time=2.2429s
batch 161 | size=128 | time=2.1513s
batch 162 | size=128 | time=2.0923s
batch 163 | size=128 | time=2.9713s
batch 164 | size=128 | time=2.9244s
batch 165 | size=128 | time=2.4347s
batch 166 | size=128 | time=2.3731s
batch 167 | size=128 | time=2.4741s
batch 168 | size=128 | time=2.5901s
batch 169 | size=128 | time=2.7992s
batch 170 | size=128 | time=2.7584s
batch 171 | size=128 | time=2.8599s
batch 172 | size=128 | time=2.7315s
batch 173 | size=128 | time=3.0091s
batch 174 | size=128 | time=3.0456s
batch 175 | size=54 | time=1.4004s

--- summary ---
total embedding time: 174.42s
total docs: 22326
dimension: 768

================ INDEXING STATS ================
Total documents embedded : 22326
Total indexing time      : 180.38 sec
Average time per doc     : 0.008079 sec
Throughput              : 123.77 docs/sec
=================================================

In [ ]:
#embed queries
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/citation_removed_queries.jsonl"
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/citation_removed_queries_embed.jsonl"

os.makedirs(os.path.dirname(query_output_file), exist_ok=True)

batch_items = []
batch_texts = []

start_time = time.time()   #

with open(query_output_file, "w", encoding="utf-8") as out_f:
    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)
            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)

            # ---- RUN BATCH ----
            if len(batch_texts) == BATCH_SIZE:

                embeddings = embed_texts(batch_texts, model)

                for it, emb in zip(batch_items, embeddings):
                    to_write = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "embedding": emb.tolist(),
                        "gold": it["relevant_subarticles"]
                    }
                    out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

                batch_items = []
                batch_texts = []

        # ---- FLUSH REMAINING ----
        if batch_texts:
            embeddings = embed_texts(batch_texts, model)

            for it, emb in zip(batch_items, embeddings):
                to_write = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "embedding": emb.tolist(),
                    "gold": it["relevant_subarticles"]
                }
                out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

end_time = time.time()   # END TIMER

print("Done! Query embeddings written to:", query_output_file)

# FINAL STATS
total_time = end_time - start_time
print(f"\nTotal embedding time: {total_time:.2f} seconds")
print(f"Average time per query: {total_time / sum(1 for _ in open(query_file)):.4f} sec")

Embedding queries: 5731it [01:57, 48.85it/s]

Done! Query embeddings written to: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/citation_removed_queries_embed.jsonl

Total embedding time: 119.81 seconds
Average time per query: 0.0209 sec

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))

query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/citation_removed_queries_embed.jsonl"

all_query_embeddings = []
all_gold_labels = []

print(f"Loading all embeddings from: {query_output_file}")

with open(query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        all_query_embeddings.append(item["embedding"])
        all_gold_labels.append(item["gold"])

# Convert to numpy matrix
query_matrix = np.array(all_query_embeddings).astype("float32")

print(f"Performing batch search for {len(query_matrix)} queries...")

# START TIMER (RETRIEVAL TIME ONLY)
start_time = time.time()

D, I = index.search(query_matrix, 100)

end_time = time.time()

# RETRIEVAL TIME METRICS
retrieval_time = end_time - start_time
num_queries = len(query_matrix)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries           : {num_queries}")
print(f"Total retrieval time    : {retrieval_time:.4f} sec")
print(f"Avg time per query      : {retrieval_time / num_queries:.6f} sec")
print(f"Throughput             : {num_queries / retrieval_time:.2f} queries/sec")
print("=================================================\n")

# FORMAT RESULTS FOR EVALUATION
all_results_for_metrics = []

for row_idx in range(len(I)):
    retrieved_ids = I[row_idx].tolist()
    all_results_for_metrics.append((retrieved_ids, all_gold_labels[row_idx]))

print("Batch retrieval complete.")

Loading all embeddings from: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/citation_removed_queries_embed.jsonl
Performing batch search for 5731 queries...

================ RETRIEVAL STATS ================
Total queries           : 5731
Total retrieval time    : 3.6836 sec
Avg time per query      : 0.000643 sec
Throughput             : 1555.81 queries/sec
=================================================

Batch retrieval complete.

#### Efficiency

In [ ]:
def measure_indexing_time(
    texts,
    ids,
    model,
    batch_size,
    save_path="/content/",
    runs=3
):
    """
    Measure dense indexing time over multiple runs.
    """

    num_docs = len(texts)

    # Warmup
    _ = embed_texts(
        texts[:min(batch_size, num_docs)],
        model
    )

    times = []

    for run in range(runs):
        print(f"\nRunning indexing experiment {run+1}/{runs}...")

        start_time = time.perf_counter()

        index, embeddings = build_faiss_pipeline(
            texts=texts,
            ids=ids,
            model=model,
            batch_size=batch_size,
            save_path=save_path
        )

        end_time = time.perf_counter()

        elapsed = end_time - start_time
        times.append(elapsed)

        print(f"Run {run+1} time: {elapsed:.2f} sec")


    avg_indexing_time = np.mean(times)

    results = {
        "num_documents": num_docs,
        "runs": runs,
        "all_times": times,
        "avg_indexing_time_sec": avg_indexing_time,
        "avg_time_per_document_sec": avg_indexing_time / num_docs,
        "throughput_docs_per_sec": num_docs / avg_indexing_time
    }

    return results

indexing_stats = measure_indexing_time(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path="/content/",
    runs=3
)

print("\n============== INDEXING STATS ==============")
print(f"Documents embedded      : {indexing_stats['num_documents']}")
print(f"Runs                    : {indexing_stats['runs']}")
print(f"Individual times        : {indexing_stats['all_times']}")
print(f"Average indexing time   : {indexing_stats['avg_indexing_time_sec']:.2f} sec")
print(f"Avg time per document   : {indexing_stats['avg_time_per_document_sec']:.6f} sec")
print(f"Throughput              : {indexing_stats['throughput_docs_per_sec']:.2f} docs/sec")
print("============================================")

Running indexing experiment 1/3...
batch 1 | size=128 | time=0.1544s
batch 2 | size=128 | time=0.1726s
batch 3 | size=128 | time=0.1911s
batch 4 | size=128 | time=0.2209s
batch 5 | size=128 | time=0.2027s
batch 6 | size=128 | time=0.2223s
batch 7 | size=128 | time=0.2255s
batch 8 | size=128 | time=0.2236s
batch 9 | size=128 | time=0.2365s
batch 10 | size=128 | time=0.2392s
batch 11 | size=128 | time=0.2521s
batch 12 | size=128 | time=0.2421s
batch 13 | size=128 | time=0.2582s
batch 14 | size=128 | time=0.2690s
batch 15 | size=128 | time=0.2681s
batch 16 | size=128 | time=0.2559s
batch 17 | size=128 | time=0.2517s
batch 18 | size=128 | time=0.2680s
batch 19 | size=128 | time=0.2893s
batch 20 | size=128 | time=0.2900s
batch 21 | size=128 | time=0.2682s
batch 22 | size=128 | time=0.2942s
batch 23 | size=128 | time=0.3041s
batch 24 | size=128 | time=0.2898s
batch 25 | size=128 | time=0.3026s
batch 26 | size=128 | time=0.2923s
batch 27 | size=128 | time=0.3174s
batch 28 | size=128 | time=0.3068s
batch 29 | size=128 | time=0.3254s
batch 30 | size=128 | time=0.3126s
batch 31 | size=128 | time=0.3359s
batch 32 | size=128 | time=0.3358s
batch 33 | size=128 | time=0.3597s
batch 34 | size=128 | time=0.3300s
batch 35 | size=128 | time=0.3312s
batch 36 | size=128 | time=0.3253s
batch 37 | size=128 | time=0.3716s
batch 38 | size=128 | time=0.3632s
batch 39 | size=128 | time=0.3492s
batch 40 | size=128 | time=0.3525s
batch 41 | size=128 | time=0.3403s
batch 42 | size=128 | time=0.3187s
batch 43 | size=128 | time=0.3974s
batch 44 | size=128 | time=0.3692s
batch 45 | size=128 | time=0.3572s
batch 46 | size=128 | time=0.3461s
batch 47 | size=128 | time=0.3868s
batch 48 | size=128 | time=0.3837s
batch 49 | size=128 | time=0.3929s
batch 50 | size=128 | time=0.3961s
batch 51 | size=128 | time=0.3775s
batch 52 | size=128 | time=0.4147s
batch 53 | size=128 | time=0.3770s
batch 54 | size=128 | time=0.4267s
batch 55 | size=128 | time=0.4029s
batch 56 | size=128 | time=0.4293s
batch 57 | size=128 | time=0.4728s
batch 58 | size=128 | time=0.4706s
batch 59 | size=128 | time=0.4167s
batch 60 | size=128 | time=0.4348s
batch 61 | size=128 | time=0.4433s
batch 62 | size=128 | time=0.4480s
batch 63 | size=128 | time=0.4662s
batch 64 | size=128 | time=0.4471s
batch 65 | size=128 | time=0.4817s
batch 66 | size=128 | time=0.4754s
batch 67 | size=128 | time=0.5587s
batch 68 | size=128 | time=0.5329s
batch 69 | size=128 | time=0.5078s
batch 70 | size=128 | time=0.5077s
batch 71 | size=128 | time=0.5172s
batch 72 | size=128 | time=0.5158s
batch 73 | size=128 | time=0.5436s
batch 74 | size=128 | time=0.5792s
batch 75 | size=128 | time=0.5377s
batch 76 | size=128 | time=0.5028s
batch 77 | size=128 | time=0.5116s
batch 78 | size=128 | time=0.5278s
batch 79 | size=128 | time=0.5109s
batch 80 | size=128 | time=0.5578s
batch 81 | size=128 | time=0.5741s
batch 82 | size=128 | time=0.5696s
batch 83 | size=128 | time=0.6219s
batch 84 | size=128 | time=0.7957s
batch 85 | size=128 | time=0.8320s
batch 86 | size=128 | time=0.8754s
batch 87 | size=128 | time=0.8205s
batch 88 | size=128 | time=0.6889s
batch 89 | size=128 | time=0.6671s
batch 90 | size=128 | time=0.6633s
batch 91 | size=128 | time=0.6563s
batch 92 | size=128 | time=0.7593s
batch 93 | size=128 | time=0.6887s
batch 94 | size=128 | time=0.6711s
batch 95 | size=128 | time=0.6865s
batch 96 | size=128 | time=0.7236s
batch 97 | size=128 | time=0.6407s
batch 98 | size=128 | time=0.6836s
batch 99 | size=128 | time=0.6935s
batch 100 | size=128 | time=0.6877s
batch 101 | size=128 | time=0.6832s
batch 102 | size=128 | time=0.7445s
batch 103 | size=128 | time=0.6848s
batch 104 | size=128 | time=0.7310s
batch 105 | size=128 | time=0.7391s
batch 106 | size=128 | time=0.8509s
batch 107 | size=128 | time=0.7908s
batch 108 | size=128 | time=0.7792s
batch 109 | size=128 | time=0.7797s
batch 110 | size=128 | time=0.8939s
batch 111 | size=128 | time=0.8338s
batch 112 | size=128 | time=0.8452s
batch 113 | size=128 | time=0.8823s
batch 114 | size=128 | time=0.9333s
batch 115 | size=128 | time=0.9467s
batch 116 | size=128 | time=0.8709s
batch 117 | size=128 | time=0.8985s
batch 118 | size=128 | time=0.9710s
batch 119 | size=128 | time=0.9288s
batch 120 | size=128 | time=1.0169s
batch 121 | size=128 | time=1.0556s
batch 122 | size=128 | time=0.9785s
batch 123 | size=128 | time=1.0969s
batch 124 | size=128 | time=1.0274s
batch 125 | size=128 | time=1.1408s
batch 126 | size=128 | time=1.1753s
batch 127 | size=128 | time=1.2262s
batch 128 | size=128 | time=1.2423s
batch 129 | size=128 | time=1.0823s
batch 130 | size=128 | time=1.1343s
batch 131 | size=128 | time=1.1964s
batch 132 | size=128 | time=1.2959s
batch 133 | size=128 | time=1.3851s
batch 134 | size=128 | time=1.3142s
batch 135 | size=128 | time=1.3874s
batch 136 | size=128 | time=1.4787s
batch 137 | size=128 | time=1.4074s
batch 138 | size=128 | time=1.5516s
batch 139 | size=128 | time=1.5250s
batch 140 | size=128 | time=1.4632s
batch 141 | size=128 | time=1.4600s
batch 142 | size=128 | time=1.5075s
batch 143 | size=128 | time=1.4994s
batch 144 | size=128 | time=1.5032s
batch 145 | size=128 | time=1.5367s
batch 146 | size=128 | time=1.7105s
batch 147 | size=128 | time=1.6963s
batch 148 | size=128 | time=1.7407s
batch 149 | size=128 | time=1.8534s
batch 150 | size=128 | time=1.8620s
batch 151 | size=128 | time=1.8108s
batch 152 | size=128 | time=1.9678s
batch 153 | size=128 | time=1.8341s
batch 154 | size=128 | time=1.9440s
batch 155 | size=128 | time=2.0439s
batch 156 | size=128 | time=2.1042s
batch 157 | size=128 | time=2.0672s
batch 158 | size=128 | time=2.1381s
batch 159 | size=128 | time=2.2180s
batch 160 | size=128 | time=2.3958s
batch 161 | size=128 | time=2.2531s
batch 162 | size=128 | time=2.4412s
batch 163 | size=128 | time=2.3739s
batch 164 | size=128 | time=2.5133s
batch 165 | size=128 | time=2.4600s
batch 166 | size=74 | time=1.4889s

--- summary ---
total embedding time: 135.68s
total docs: 21194
dimension: 768
Run 1 time: 136.18 sec

Running indexing experiment 2/3...
batch 1 | size=128 | time=0.1794s
batch 2 | size=128 | time=0.2009s
batch 3 | size=128 | time=0.2303s
batch 4 | size=128 | time=0.2585s
batch 5 | size=128 | time=0.2387s
batch 6 | size=128 | time=0.2626s
batch 7 | size=128 | time=0.2647s
batch 8 | size=128 | time=0.2616s
batch 9 | size=128 | time=0.2729s
batch 10 | size=128 | time=0.2732s
batch 11 | size=128 | time=0.2854s
batch 12 | size=128 | time=0.2889s
batch 13 | size=128 | time=0.2992s
batch 14 | size=128 | time=0.3111s
batch 15 | size=128 | time=0.3075s
batch 16 | size=128 | time=0.2863s
batch 17 | size=128 | time=0.2813s
batch 18 | size=128 | time=0.2983s
batch 19 | size=128 | time=0.3275s
batch 20 | size=128 | time=0.3218s
batch 21 | size=128 | time=0.2994s
batch 22 | size=128 | time=0.3224s
batch 23 | size=128 | time=0.3384s
batch 24 | size=128 | time=0.3221s
batch 25 | size=128 | time=0.3359s
batch 26 | size=128 | time=0.3262s
batch 27 | size=128 | time=0.3496s
batch 28 | size=128 | time=0.3311s
batch 29 | size=128 | time=0.3486s
batch 30 | size=128 | time=0.3328s
batch 31 | size=128 | time=0.3447s
batch 32 | size=128 | time=0.3488s
batch 33 | size=128 | time=0.3659s
batch 34 | size=128 | time=0.3513s
batch 35 | size=128 | time=0.3475s
batch 36 | size=128 | time=0.3428s
batch 37 | size=128 | time=0.3915s
batch 38 | size=128 | time=0.3885s
batch 39 | size=128 | time=0.3653s
batch 40 | size=128 | time=0.3726s
batch 41 | size=128 | time=0.3636s
batch 42 | size=128 | time=0.3498s
batch 43 | size=128 | time=0.4423s
batch 44 | size=128 | time=0.4198s
batch 45 | size=128 | time=0.4124s
batch 46 | size=128 | time=0.3873s
batch 47 | size=128 | time=0.4467s
batch 48 | size=128 | time=0.4404s
batch 49 | size=128 | time=0.4548s
batch 50 | size=128 | time=0.4582s
batch 51 | size=128 | time=0.4380s
batch 52 | size=128 | time=0.4794s
batch 53 | size=128 | time=0.4436s
batch 54 | size=128 | time=0.4694s
batch 55 | size=128 | time=0.4406s
batch 56 | size=128 | time=0.4696s
batch 57 | size=128 | time=0.5221s
batch 58 | size=128 | time=0.5292s
batch 59 | size=128 | time=0.4588s
batch 60 | size=128 | time=0.4848s
batch 61 | size=128 | time=0.4997s
batch 62 | size=128 | time=0.4960s
batch 63 | size=128 | time=0.5100s
batch 64 | size=128 | time=0.4921s
batch 65 | size=128 | time=0.5328s
batch 66 | size=128 | time=0.5068s
batch 67 | size=128 | time=0.5264s
batch 68 | size=128 | time=0.5627s
batch 69 | size=128 | time=0.5427s
batch 70 | size=128 | time=0.5320s
batch 71 | size=128 | time=0.5415s
batch 72 | size=128 | time=0.5383s
batch 73 | size=128 | time=0.5748s
batch 74 | size=128 | time=0.6535s
batch 75 | size=128 | time=0.6283s
batch 76 | size=128 | time=0.5781s
batch 77 | size=128 | time=0.5893s
batch 78 | size=128 | time=0.6048s
batch 79 | size=128 | time=0.5820s
batch 80 | size=128 | time=0.6444s
batch 81 | size=128 | time=0.5909s
batch 82 | size=128 | time=0.5983s
batch 83 | size=128 | time=0.6252s
batch 84 | size=128 | time=0.6338s
batch 85 | size=128 | time=0.6436s
batch 86 | size=128 | time=0.7105s
batch 87 | size=128 | time=0.6604s
batch 88 | size=128 | time=0.6671s
batch 89 | size=128 | time=0.7178s
batch 90 | size=128 | time=0.6962s
batch 91 | size=128 | time=0.6915s
batch 92 | size=128 | time=0.8035s
batch 93 | size=128 | time=0.7298s
batch 94 | size=128 | time=0.7076s
batch 95 | size=128 | time=0.7240s
batch 96 | size=128 | time=0.8308s
batch 97 | size=128 | time=0.7418s
batch 98 | size=128 | time=0.7901s
batch 99 | size=128 | time=0.8108s
batch 100 | size=128 | time=0.8022s
batch 101 | size=128 | time=0.7581s
batch 102 | size=128 | time=0.8179s
batch 103 | size=128 | time=0.7485s
batch 104 | size=128 | time=0.7971s
batch 105 | size=128 | time=0.7950s
batch 106 | size=128 | time=0.9320s
batch 107 | size=128 | time=0.8650s
batch 108 | size=128 | time=0.8492s
batch 109 | size=128 | time=0.8425s
batch 110 | size=128 | time=0.9235s
batch 111 | size=128 | time=0.8641s
batch 112 | size=128 | time=0.8783s
batch 113 | size=128 | time=0.9532s
batch 114 | size=128 | time=1.0419s
batch 115 | size=128 | time=1.0644s
batch 116 | size=128 | time=0.9978s
batch 117 | size=128 | time=1.0033s
batch 118 | size=128 | time=1.0477s
batch 119 | size=128 | time=1.0032s
batch 120 | size=128 | time=1.1083s
batch 121 | size=128 | time=1.1496s
batch 122 | size=128 | time=1.0615s
batch 123 | size=128 | time=1.1959s
batch 124 | size=128 | time=1.1166s
batch 125 | size=128 | time=1.1880s
batch 126 | size=128 | time=1.2348s
batch 127 | size=128 | time=1.3493s
batch 128 | size=128 | time=1.3681s
batch 129 | size=128 | time=1.2036s
batch 130 | size=128 | time=1.2557s
batch 131 | size=128 | time=1.3020s
batch 132 | size=128 | time=1.3997s
batch 133 | size=128 | time=1.5088s
batch 134 | size=128 | time=1.4328s
batch 135 | size=128 | time=1.5012s
batch 136 | size=128 | time=1.5994s
batch 137 | size=128 | time=1.5302s
batch 138 | size=128 | time=1.7017s
batch 139 | size=128 | time=1.6178s
batch 140 | size=128 | time=1.5739s
batch 141 | size=128 | time=1.5704s
batch 142 | size=128 | time=1.6201s
batch 143 | size=128 | time=1.6164s
batch 144 | size=128 | time=1.6268s
batch 145 | size=128 | time=1.6883s
batch 146 | size=128 | time=1.8043s
batch 147 | size=128 | time=1.8284s
batch 148 | size=128 | time=1.8093s
batch 149 | size=128 | time=1.9805s
batch 150 | size=128 | time=1.9899s
batch 151 | size=128 | time=1.9404s
batch 152 | size=128 | time=2.1254s
batch 153 | size=128 | time=2.0607s
batch 154 | size=128 | time=2.0886s
batch 155 | size=128 | time=2.0839s
batch 156 | size=128 | time=2.2719s
batch 157 | size=128 | time=2.2462s
batch 158 | size=128 | time=2.3072s
batch 159 | size=128 | time=2.4471s
batch 160 | size=128 | time=2.6839s
batch 161 | size=128 | time=2.3124s
batch 162 | size=128 | time=2.5707s
batch 163 | size=128 | time=2.5623s
batch 164 | size=128 | time=2.7328s
batch 165 | size=128 | time=2.7698s
batch 166 | size=74 | time=1.6483s

--- summary ---
total embedding time: 146.57s
total docs: 21194
dimension: 768
Run 2 time: 146.97 sec

Running indexing experiment 3/3...
batch 1 | size=128 | time=0.1729s
batch 2 | size=128 | time=0.2043s
batch 3 | size=128 | time=0.2279s
batch 4 | size=128 | time=0.2535s
batch 5 | size=128 | time=0.2468s
batch 6 | size=128 | time=0.2620s
batch 7 | size=128 | time=0.2619s
batch 8 | size=128 | time=0.2528s
batch 9 | size=128 | time=0.2763s
batch 10 | size=128 | time=0.2775s
batch 11 | size=128 | time=0.2892s
batch 12 | size=128 | time=0.2818s
batch 13 | size=128 | time=0.2980s
batch 14 | size=128 | time=0.3166s
batch 15 | size=128 | time=0.3161s
batch 16 | size=128 | time=0.3082s
batch 17 | size=128 | time=0.2998s
batch 18 | size=128 | time=0.3187s
batch 19 | size=128 | time=0.3430s
batch 20 | size=128 | time=0.3418s
batch 21 | size=128 | time=0.3224s
batch 22 | size=128 | time=0.3455s
batch 23 | size=128 | time=0.3520s
batch 24 | size=128 | time=0.3367s
batch 25 | size=128 | time=0.3623s
batch 26 | size=128 | time=0.3474s
batch 27 | size=128 | time=0.3716s
batch 28 | size=128 | time=0.3482s
batch 29 | size=128 | time=0.3677s
batch 30 | size=128 | time=0.3533s
batch 31 | size=128 | time=0.3814s
batch 32 | size=128 | time=0.3900s
batch 33 | size=128 | time=0.4061s
batch 34 | size=128 | time=0.3876s
batch 35 | size=128 | time=0.3855s
batch 36 | size=128 | time=0.3784s
batch 37 | size=128 | time=0.4301s
batch 38 | size=128 | time=0.4230s
batch 39 | size=128 | time=0.4054s
batch 40 | size=128 | time=0.4079s
batch 41 | size=128 | time=0.4017s
batch 42 | size=128 | time=0.3769s
batch 43 | size=128 | time=0.4734s
batch 44 | size=128 | time=0.4413s
batch 45 | size=128 | time=0.4212s
batch 46 | size=128 | time=0.3961s
batch 47 | size=128 | time=0.4559s
batch 48 | size=128 | time=0.4490s
batch 49 | size=128 | time=0.4693s
batch 50 | size=128 | time=0.4681s
batch 51 | size=128 | time=0.4468s
batch 52 | size=128 | time=0.4888s
batch 53 | size=128 | time=0.4557s
batch 54 | size=128 | time=0.4957s
batch 55 | size=128 | time=0.4769s
batch 56 | size=128 | time=0.5013s
batch 57 | size=128 | time=0.5597s
batch 58 | size=128 | time=0.5520s
batch 59 | size=128 | time=0.4861s
batch 60 | size=128 | time=0.5109s
batch 61 | size=128 | time=0.5242s
batch 62 | size=128 | time=0.5202s
batch 63 | size=128 | time=0.5643s
batch 64 | size=128 | time=0.5416s
batch 65 | size=128 | time=0.5854s
batch 66 | size=128 | time=0.5470s
batch 67 | size=128 | time=0.5829s
batch 68 | size=128 | time=0.6163s
batch 69 | size=128 | time=0.5953s
batch 70 | size=128 | time=0.5673s
batch 71 | size=128 | time=0.5633s
batch 72 | size=128 | time=0.5618s
batch 73 | size=128 | time=0.5937s
batch 74 | size=128 | time=0.6632s
batch 75 | size=128 | time=0.6281s
batch 76 | size=128 | time=0.5781s
batch 77 | size=128 | time=0.5910s
batch 78 | size=128 | time=0.6087s
batch 79 | size=128 | time=0.5894s
batch 80 | size=128 | time=0.6444s
batch 81 | size=128 | time=0.6247s
batch 82 | size=128 | time=0.6282s
batch 83 | size=128 | time=0.6568s
batch 84 | size=128 | time=0.6662s
batch 85 | size=128 | time=0.6764s
batch 86 | size=128 | time=0.7474s
batch 87 | size=128 | time=0.7181s
batch 88 | size=128 | time=0.7154s
batch 89 | size=128 | time=0.7706s
batch 90 | size=128 | time=0.7505s
batch 91 | size=128 | time=0.7464s
batch 92 | size=128 | time=0.8496s
batch 93 | size=128 | time=0.7532s
batch 94 | size=128 | time=0.7430s
batch 95 | size=128 | time=0.7513s
batch 96 | size=128 | time=0.8375s
batch 97 | size=128 | time=0.7411s
batch 98 | size=128 | time=0.7904s
batch 99 | size=128 | time=0.7930s
batch 100 | size=128 | time=0.7876s
batch 101 | size=128 | time=0.7833s
batch 102 | size=128 | time=0.8464s
batch 103 | size=128 | time=0.7771s
batch 104 | size=128 | time=0.8269s
batch 105 | size=128 | time=0.8624s
batch 106 | size=128 | time=1.0029s
batch 107 | size=128 | time=0.9171s
batch 108 | size=128 | time=0.9339s
batch 109 | size=128 | time=0.9133s
batch 110 | size=128 | time=0.9649s
batch 111 | size=128 | time=0.9011s
batch 112 | size=128 | time=0.9024s
batch 113 | size=128 | time=0.9397s
batch 114 | size=128 | time=1.0206s
batch 115 | size=128 | time=1.0586s
batch 116 | size=128 | time=0.9895s
batch 117 | size=128 | time=0.9977s
batch 118 | size=128 | time=1.0805s
batch 119 | size=128 | time=1.0406s
batch 120 | size=128 | time=1.1884s
batch 121 | size=128 | time=1.2402s
batch 122 | size=128 | time=1.1586s
batch 123 | size=128 | time=1.2658s
batch 124 | size=128 | time=1.1546s
batch 125 | size=128 | time=1.2443s
batch 126 | size=128 | time=1.2851s
batch 127 | size=128 | time=1.3322s
batch 128 | size=128 | time=1.3617s
batch 129 | size=128 | time=1.2170s
batch 130 | size=128 | time=1.3022s
batch 131 | size=128 | time=1.3865s
batch 132 | size=128 | time=1.5114s
batch 133 | size=128 | time=1.6162s
batch 134 | size=128 | time=1.4618s
batch 135 | size=128 | time=1.5543s
batch 136 | size=128 | time=1.6293s
batch 137 | size=128 | time=1.5046s
batch 138 | size=128 | time=1.6615s
batch 139 | size=128 | time=1.6387s
batch 140 | size=128 | time=1.6718s
batch 141 | size=128 | time=1.7001s
batch 142 | size=128 | time=1.7432s
batch 143 | size=128 | time=1.6568s
batch 144 | size=128 | time=1.6650s
batch 145 | size=128 | time=1.6915s
batch 146 | size=128 | time=1.7775s
batch 147 | size=128 | time=1.8079s
batch 148 | size=128 | time=1.9012s
batch 149 | size=128 | time=2.1474s
batch 150 | size=128 | time=2.0886s
batch 151 | size=128 | time=1.9908s
batch 152 | size=128 | time=2.1920s
batch 153 | size=128 | time=2.0197s
batch 154 | size=128 | time=2.0544s
batch 155 | size=128 | time=2.1974s
batch 156 | size=128 | time=2.4434s
batch 157 | size=128 | time=2.3288s
batch 158 | size=128 | time=2.3424s
batch 159 | size=128 | time=2.4557s
batch 160 | size=128 | time=2.6008s
batch 161 | size=128 | time=2.4264s
batch 162 | size=128 | time=2.7286s
batch 163 | size=128 | time=2.6160s
batch 164 | size=128 | time=2.7380s
batch 165 | size=128 | time=2.6676s
batch 166 | size=74 | time=1.6216s

--- summary ---
total embedding time: 151.54s
total docs: 21194
dimension: 768
Run 3 time: 152.03 sec

============== INDEXING STATS ==============
Documents embedded      : 21194
Runs                    : 3
Individual times        : [136.18130968100013, 146.96722869999985, 152.0281596650002]
Average indexing time   : 145.06 sec
Avg time per document   : 0.006844 sec
Throughput              : 146.11 docs/sec
============================================

In [ ]:
import time
import numpy as np


def measure_dense_retrieval_latency(
    index,
    queries,
    embedding_model,
    top_k=100,
    warmup=True,
    runs=3
):
    """
    Measure end-to-end dense retrieval latency:
    text query -> embedding -> FAISS search
    """

    num_queries = len(queries)

    # Warm-up
    if warmup:
        emb = embedding_model.encode(
            [queries[0]],
            convert_to_numpy=True
        ).astype("float32")

        index.search(emb, top_k)

    times = []

    for _ in tqdm(range(runs)):

        start = time.perf_counter()

        for query in queries:

            # Query embedding
            query_embedding = embedding_model.encode(
                [query],
                convert_to_numpy=True
            ).astype("float32")

            # Retrieval
            index.search(query_embedding, top_k)

        end = time.perf_counter()

        times.append(end - start)


    avg_time = np.mean(times)

    return {
        "num_queries": num_queries,
        "top_k": top_k,
        "runs": runs,
        "total_time_sec": avg_time,
        "avg_latency_per_query_ms": (avg_time / num_queries) * 1000,
        "queries_per_second": num_queries / avg_time,
        "all_runs": times
    }

#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=3
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

100%|██████████| 3/3 [10:12<00:00, 204.03s/it]

============== RETRIEVAL STATS ==============
Total queries           : 5731
Top-k                   : 100
Runs                    : 3
Total time              : 204.03 sec
Avg latency per query   : 35.60 ms
Throughput              : 28.09 queries/sec
============================================

In [ ]:
import os

def get_index_size(index_path):
    """
    Returns FAISS index size in MB/GB.
    """
    size_bytes = os.path.getsize(index_path)

    return {
        "size_bytes": size_bytes,
        "size_MB": size_bytes / (1024 ** 2),
        "size_GB": size_bytes / (1024 ** 3)
    }

index_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/sa_faiss.index"

index_size = get_index_size(index_file)

print(f"Index size: {index_size['size_MB']:.2f} MB")
print(f"Index size: {index_size['size_GB']:.3f} GB")

Index size: 65.58 MB
Index size: 0.064 GB

#### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.2396  0.0882     NaN      NaN
1   10  0.3068  0.0629  0.1761    0.203
2  100  0.5494  0.0126     NaN      NaN

## Multilingual

### a. BGE-M3

In [ ]:
!pip install faiss-gpu

Collecting faiss-gpu
  Downloading faiss_gpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (26.2)
Requirement already satisfied: nvidia-cuda-runtime-cu12<13,>=12.6 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (12.8.90)
Requirement already satisfied: nvidia-cublas-cu12<13,>=12.6 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (12.8.4.1)
Requirement already satisfied: nvidia-curand-cu12<11,>=10.3.7 in /usr/local/lib/python3.12/dist-packages (from faiss-gpu) (10.3.9.90)
Downloading faiss_gpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (134.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 MB 6.5 MB/s eta 0:00:00
Installing collected packages: faiss-gpu
Successfully installed faiss-gpu-1.14.3

In [ ]:
import numpy as np
import pandas as pd
import faiss
import os
import torch
from transformers import AutoTokenizer, AutoModel
import time
import json
from tqdm import tqdm

In [ ]:
model_name = "BAAI/bge-m3"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)
model.eval()

In [ ]:
def mean_pooling(last_hidden_state, attention_mask):
    mask = attention_mask.unsqueeze(-1).expand(last_hidden_state.size()).float()
    summed = torch.sum(last_hidden_state * mask, dim=1)
    counts = torch.clamp(mask.sum(dim=1), min=1e-9)
    return summed / counts

def embed_texts(batch_texts, model, tokenizer):
    """
    BGE-M3 HF embedding (dense only)
    """
    inputs = tokenizer(
        batch_texts,
        padding=True,
        truncation=True,
        return_tensors="pt",
        max_length=512
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    emb = mean_pooling(outputs.last_hidden_state, inputs["attention_mask"])

    # normalize for cosine similarity
    emb = torch.nn.functional.normalize(emb, p=2, dim=1)

    return emb.cpu().numpy().astype("float32")

def embed_query(text):
    inputs = tokenizer(
        [text],
        padding=True,
        truncation=True,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)

    emb = mean_pooling(outputs.last_hidden_state, inputs["attention_mask"])
    emb = torch.nn.functional.normalize(emb, p=2, dim=1)

    return emb.cpu().numpy().astype("float32")

In [ ]:
def build_faiss_pipeline(
    texts,
    ids,
    model,
    tokenizer,
    batch_size=32,
    save_path=None
):
    all_embeddings = []
    total_time = 0.0

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        start = time.time()

        emb = embed_texts(batch, model, tokenizer)

        end = time.time()
        total_time += (end - start)

        print(f"batch {i//batch_size + 1} | size={len(batch)} | time={end-start:.4f}s")

        all_embeddings.append(emb)

    embeddings = np.concatenate(all_embeddings, axis=0).astype("float32")

    dim = np.array(embeddings).shape[1]
    index = faiss.IndexFlatIP(dim)
    index = faiss.IndexIDMap(index)
    index.add_with_ids(embeddings, ids)

    # --- SAVE ARTIFACTS ---
    if save_path:
        os.makedirs(save_path, exist_ok=True)

        # 1. save faiss index
        faiss.write_index(index, os.path.join(save_path, "sa_faiss.index"))

        # 2. save embeddings
        np.save(os.path.join(save_path, "sa_embeddings.npy"), embeddings)

    print("\n--- summary ---")
    print(f"total embedding time: {total_time:.2f}s")
    print(f"total docs: {len(ids)}")
    print(f"dimension: {dim}")

    return index,embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

index, embeddings = build_faiss_pipeline(
    texts=texts,
    ids=ids,
    model=model,
    tokenizer=tokenizer,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

Loading documents...
Total documents: 22326
batch 1 | size=128 | time=0.8566s
batch 2 | size=128 | time=0.5927s
batch 3 | size=128 | time=0.6807s
batch 4 | size=128 | time=0.7725s
batch 5 | size=128 | time=0.7448s
batch 6 | size=128 | time=0.9348s
batch 7 | size=128 | time=0.9137s
batch 8 | size=128 | time=0.8404s
batch 9 | size=128 | time=0.9469s
batch 10 | size=128 | time=0.9612s
batch 11 | size=128 | time=0.8957s
batch 12 | size=128 | time=1.0125s
batch 13 | size=128 | time=1.0022s
batch 14 | size=128 | time=1.2698s
batch 15 | size=128 | time=1.0956s
batch 16 | size=128 | time=0.9933s
batch 17 | size=128 | time=0.9965s
batch 18 | size=128 | time=1.0160s
batch 19 | size=128 | time=1.1392s
batch 20 | size=128 | time=1.1401s
batch 21 | size=128 | time=1.1505s
batch 22 | size=128 | time=1.0626s
batch 23 | size=128 | time=1.2701s
batch 24 | size=128 | time=1.2048s
batch 25 | size=128 | time=1.3048s
batch 26 | size=128 | time=1.1494s
batch 27 | size=128 | time=1.3445s
batch 28 | size=128 | time=1.2186s
batch 29 | size=128 | time=1.1551s
batch 30 | size=128 | time=1.2459s
batch 31 | size=128 | time=1.1742s
batch 32 | size=128 | time=1.3747s
batch 33 | size=128 | time=1.3596s
batch 34 | size=128 | time=1.3540s
batch 35 | size=128 | time=1.3651s
batch 36 | size=128 | time=1.3623s
batch 37 | size=128 | time=1.6465s
batch 38 | size=128 | time=1.5207s
batch 39 | size=128 | time=1.5488s
batch 40 | size=128 | time=1.4979s
batch 41 | size=128 | time=1.4551s
batch 42 | size=128 | time=1.4413s
batch 43 | size=128 | time=1.3771s
batch 44 | size=128 | time=2.0207s
batch 45 | size=128 | time=1.6209s
batch 46 | size=128 | time=1.6286s
batch 47 | size=128 | time=1.7967s
batch 48 | size=128 | time=1.6943s
batch 49 | size=128 | time=1.7286s
batch 50 | size=128 | time=1.6796s
batch 51 | size=128 | time=1.7849s
batch 52 | size=128 | time=2.0692s
batch 53 | size=128 | time=2.1543s
batch 54 | size=128 | time=1.8953s
batch 55 | size=128 | time=1.8806s
batch 56 | size=128 | time=1.9576s
batch 57 | size=128 | time=2.2469s
batch 58 | size=128 | time=2.5651s
batch 59 | size=128 | time=2.5024s
batch 60 | size=128 | time=2.4602s
batch 61 | size=128 | time=2.4015s
batch 62 | size=128 | time=2.3349s
batch 63 | size=128 | time=2.4307s
batch 64 | size=128 | time=2.2323s
batch 65 | size=128 | time=2.1939s
batch 66 | size=128 | time=2.1659s
batch 67 | size=128 | time=2.1830s
batch 68 | size=128 | time=2.5769s
batch 69 | size=128 | time=2.2616s
batch 70 | size=128 | time=2.3353s
batch 71 | size=128 | time=2.2873s
batch 72 | size=128 | time=2.4531s
batch 73 | size=128 | time=2.2739s
batch 74 | size=128 | time=2.6196s
batch 75 | size=128 | time=2.0690s
batch 76 | size=128 | time=2.3894s
batch 77 | size=128 | time=2.1858s
batch 78 | size=128 | time=2.5212s
batch 79 | size=128 | time=2.2885s
batch 80 | size=128 | time=2.6399s
batch 81 | size=128 | time=2.6514s
batch 82 | size=128 | time=2.4757s
batch 83 | size=128 | time=2.2932s
batch 84 | size=128 | time=2.6087s
batch 85 | size=128 | time=2.6398s
batch 86 | size=128 | time=2.5913s
batch 87 | size=128 | time=2.6970s
batch 88 | size=128 | time=2.8968s
batch 89 | size=128 | time=2.7300s
batch 90 | size=128 | time=2.7027s
batch 91 | size=128 | time=3.1045s
batch 92 | size=128 | time=3.0115s
batch 93 | size=128 | time=2.7161s
batch 94 | size=128 | time=2.9878s
batch 95 | size=128 | time=2.6983s
batch 96 | size=128 | time=3.1552s
batch 97 | size=128 | time=3.0695s
batch 98 | size=128 | time=3.0067s
batch 99 | size=128 | time=3.1884s
batch 100 | size=128 | time=3.2306s
batch 101 | size=128 | time=3.1824s
batch 102 | size=128 | time=2.8398s
batch 103 | size=128 | time=3.2678s
batch 104 | size=128 | time=2.9324s
batch 105 | size=128 | time=3.5749s
batch 106 | size=128 | time=3.1220s
batch 107 | size=128 | time=3.0890s
batch 108 | size=128 | time=3.2037s
batch 109 | size=128 | time=3.0358s
batch 110 | size=128 | time=3.2188s
batch 111 | size=128 | time=3.5021s
batch 112 | size=128 | time=3.6349s
batch 113 | size=128 | time=3.6346s
batch 114 | size=128 | time=3.8027s
batch 115 | size=128 | time=3.4646s
batch 116 | size=128 | time=3.6417s
batch 117 | size=128 | time=3.7930s
batch 118 | size=128 | time=3.6432s
batch 119 | size=128 | time=3.4635s
batch 120 | size=128 | time=4.2226s
batch 121 | size=128 | time=4.0555s
batch 122 | size=128 | time=4.3184s
batch 123 | size=128 | time=4.0827s
batch 124 | size=128 | time=4.1490s
batch 125 | size=128 | time=4.0731s
batch 126 | size=128 | time=4.3465s
batch 127 | size=128 | time=4.5774s
batch 128 | size=128 | time=4.3676s
batch 129 | size=128 | time=4.4115s
batch 130 | size=128 | time=5.8001s
batch 131 | size=128 | time=4.8914s
batch 132 | size=128 | time=4.8266s
batch 133 | size=128 | time=5.3675s
batch 134 | size=128 | time=5.8098s
batch 135 | size=128 | time=5.1915s
batch 136 | size=128 | time=5.3792s
batch 137 | size=128 | time=5.0317s
batch 138 | size=128 | time=5.4338s
batch 139 | size=128 | time=5.7328s
batch 140 | size=128 | time=5.7879s
batch 141 | size=128 | time=5.4774s
batch 142 | size=128 | time=6.1154s
batch 143 | size=128 | time=7.1189s
batch 144 | size=128 | time=5.7743s
batch 145 | size=128 | time=6.0062s
batch 146 | size=128 | time=6.7362s
batch 147 | size=128 | time=6.2042s
batch 148 | size=128 | time=6.2475s
batch 149 | size=128 | time=6.5791s
batch 150 | size=128 | time=6.5443s
batch 151 | size=128 | time=6.4960s
batch 152 | size=128 | time=6.5959s
batch 153 | size=128 | time=7.2112s
batch 154 | size=128 | time=7.4092s
batch 155 | size=128 | time=7.2963s
batch 156 | size=128 | time=7.4782s
batch 157 | size=128 | time=9.5254s
batch 158 | size=128 | time=8.6877s
batch 159 | size=128 | time=7.9342s
batch 160 | size=128 | time=9.1037s
batch 161 | size=128 | time=7.8784s
batch 162 | size=128 | time=7.7940s
batch 163 | size=128 | time=9.0969s
batch 164 | size=128 | time=10.1333s
batch 165 | size=128 | time=9.2864s
batch 166 | size=128 | time=9.9032s
batch 167 | size=128 | time=9.4845s
batch 168 | size=128 | time=10.0843s
batch 169 | size=128 | time=9.5998s
batch 170 | size=128 | time=10.7571s
batch 171 | size=128 | time=10.4166s
batch 172 | size=128 | time=10.6128s
batch 173 | size=128 | time=10.3706s
batch 174 | size=128 | time=13.5466s
batch 175 | size=54 | time=5.4938s

--- summary ---
total embedding time: 637.28s
total docs: 22326
dimension: 1024

================ INDEXING STATS ================
Total documents embedded : 22326
Total indexing time      : 649.89 sec
Average time per doc     : 0.029109 sec
Throughput              : 34.35 docs/sec
=================================================

In [ ]:
#embed queries
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/queries_embed.jsonl"

os.makedirs(os.path.dirname(query_output_file), exist_ok=True)

batch_items = []
batch_texts = []

start_time = time.time()

with open(query_output_file, "w", encoding="utf-8") as out_f:
    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)
            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)

            # ---- RUN BATCH ----
            if len(batch_texts) == BATCH_SIZE:

                embeddings = embed_texts(batch_texts, model, tokenizer)

                for it, emb in zip(batch_items, embeddings):
                    to_write = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "embedding": emb.tolist(),
                        "gold": it["relevant_subarticles"]
                    }
                    out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

                batch_items = []
                batch_texts = []

        # ---- FLUSH REMAINING ----
        if batch_texts:
            embeddings = embed_texts(batch_texts, model, tokenizer)

            for it, emb in zip(batch_items, embeddings):
                to_write = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "embedding": emb.tolist(),
                    "gold": it["relevant_subarticles"]
                }
                out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

end_time = time.time()   # END TIMER

print("Done! Query embeddings written to:", query_output_file)

# FINAL STATS
total_time = end_time - start_time
print(f"\nTotal embedding time: {total_time:.2f} seconds")
print(f"Average time per query: {total_time / sum(1 for _ in open(query_file)):.4f} sec")

Embedding queries: 5731it [10:09,  9.40it/s]

Done! Query embeddings written to: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/queries_embed.jsonl

Total embedding time: 620.42 seconds
Average time per query: 0.1083 sec

In [ ]:
import torch
import gc

gc.collect()
torch.cuda.empty_cache()

torch.cuda.ipc_collect()

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))


query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/queries_embed.jsonl"

all_query_embeddings = []
all_gold_labels = []

print(f"Loading all embeddings from: {query_output_file}")

with open(query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        all_query_embeddings.append(item["embedding"])
        all_gold_labels.append(item["gold"])

# Convert to numpy matrix
query_matrix = np.array(all_query_embeddings).astype("float32")

print(f"Performing batch search for {len(query_matrix)} queries...")

# START TIMER (RETRIEVAL TIME ONLY)
start_time = time.time()

D, I = index.search(query_matrix, 100)

end_time = time.time()

# RETRIEVAL TIME METRICS
retrieval_time = end_time - start_time
num_queries = len(query_matrix)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries           : {num_queries}")
print(f"Total retrieval time    : {retrieval_time:.4f} sec")
print(f"Avg time per query      : {retrieval_time / num_queries:.6f} sec")
print(f"Throughput             : {num_queries / retrieval_time:.2f} queries/sec")
print("=================================================\n")

# FORMAT RESULTS FOR EVALUATION
all_results_for_metrics = []

for row_idx in range(len(I)):
    retrieved_ids = I[row_idx].tolist()
    all_results_for_metrics.append((retrieved_ids, all_gold_labels[row_idx]))

print("Batch retrieval complete.")

Loading all embeddings from: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/queries_embed.jsonl
Performing batch search for 5731 queries...

================ RETRIEVAL STATS ================
Total queries           : 5731
Total retrieval time    : 4.7179 sec
Avg time per query      : 0.000823 sec
Throughput             : 1214.73 queries/sec
=================================================

Batch retrieval complete.

#### Efficiency

In [ ]:
def measure_indexing_time(
    texts,
    ids,
    model,
    tokenizer,
    batch_size,
    save_path="/content/",
    runs=3
):
    """
    Measure dense indexing time over multiple runs.
    """

    num_docs = len(texts)

    # Warmup
    _ = embed_texts(
        texts[:min(batch_size, num_docs)],
        model,
        tokenizer=tokenizer
    )

    times = []

    for run in range(runs):
        print(f"\nRunning indexing experiment {run+1}/{runs}...")

        start_time = time.perf_counter()

        index, embeddings = build_faiss_pipeline(
            texts=texts,
            ids=ids,
            model=model,
            tokenizer=tokenizer,
            batch_size=batch_size,
            save_path=save_path
        )

        end_time = time.perf_counter()

        elapsed = end_time - start_time
        times.append(elapsed)

        print(f"Run {run+1} time: {elapsed:.2f} sec")


    avg_indexing_time = np.mean(times)

    results = {
        "num_documents": num_docs,
        "runs": runs,
        "all_times": times,
        "avg_indexing_time_sec": avg_indexing_time,
        "avg_time_per_document_sec": avg_indexing_time / num_docs,
        "throughput_docs_per_sec": num_docs / avg_indexing_time
    }

    return results

indexing_stats = measure_indexing_time(
    texts=texts,
    ids=ids,
    model=model,
    tokenizer=tokenizer,
    batch_size=BATCH_SIZE,
    save_path="/content/",
    runs=3
)

print("\n============== INDEXING STATS ==============")
print(f"Documents embedded      : {indexing_stats['num_documents']}")
print(f"Runs                    : {indexing_stats['runs']}")
print(f"Individual times        : {indexing_stats['all_times']}")
print(f"Average indexing time   : {indexing_stats['avg_indexing_time_sec']:.2f} sec")
print(f"Avg time per document   : {indexing_stats['avg_time_per_document_sec']:.6f} sec")
print(f"Throughput              : {indexing_stats['throughput_docs_per_sec']:.2f} docs/sec")
print("============================================")

Running indexing experiment 1/3...
batch 1 | size=128 | time=0.6105s
batch 2 | size=128 | time=0.7091s
batch 3 | size=128 | time=0.7245s
batch 4 | size=128 | time=0.8603s
batch 5 | size=128 | time=0.7523s
batch 6 | size=128 | time=0.8443s
batch 7 | size=128 | time=0.8288s
batch 8 | size=128 | time=0.7427s
batch 9 | size=128 | time=0.8414s
batch 10 | size=128 | time=0.9084s
batch 11 | size=128 | time=0.8620s
batch 12 | size=128 | time=0.9602s
batch 13 | size=128 | time=0.9736s
batch 14 | size=128 | time=1.1999s
batch 15 | size=128 | time=1.0833s
batch 16 | size=128 | time=0.9733s
batch 17 | size=128 | time=1.1291s
batch 18 | size=128 | time=1.1298s
batch 19 | size=128 | time=1.1289s
batch 20 | size=128 | time=1.1462s
batch 21 | size=128 | time=1.0324s
batch 22 | size=128 | time=1.0359s
batch 23 | size=128 | time=1.2056s
batch 24 | size=128 | time=1.1318s
batch 25 | size=128 | time=1.2481s
batch 26 | size=128 | time=1.2027s
batch 27 | size=128 | time=1.0663s
batch 28 | size=128 | time=1.1482s
batch 29 | size=128 | time=1.2172s
batch 30 | size=128 | time=1.2374s
batch 31 | size=128 | time=1.4459s
batch 32 | size=128 | time=1.2790s
batch 33 | size=128 | time=1.2527s
batch 34 | size=128 | time=1.2455s
batch 35 | size=128 | time=1.1603s
batch 36 | size=128 | time=1.3493s
batch 37 | size=128 | time=1.3266s
batch 38 | size=128 | time=1.2805s
batch 39 | size=128 | time=1.2530s
batch 40 | size=128 | time=1.3255s
batch 41 | size=128 | time=1.4239s
batch 42 | size=128 | time=1.6149s
batch 43 | size=128 | time=1.7820s
batch 44 | size=128 | time=1.4537s
batch 45 | size=128 | time=1.4977s
batch 46 | size=128 | time=1.4065s
batch 47 | size=128 | time=1.4522s
batch 48 | size=128 | time=1.5074s
batch 49 | size=128 | time=1.5205s
batch 50 | size=128 | time=1.8946s
batch 51 | size=128 | time=1.7406s
batch 52 | size=128 | time=1.6562s
batch 53 | size=128 | time=1.6165s
batch 54 | size=128 | time=1.8441s
batch 55 | size=128 | time=1.5510s
batch 56 | size=128 | time=2.0206s
batch 57 | size=128 | time=1.8601s
batch 58 | size=128 | time=2.0654s
batch 59 | size=128 | time=1.8716s
batch 60 | size=128 | time=1.7169s
batch 61 | size=128 | time=1.9447s
batch 62 | size=128 | time=1.9369s
batch 63 | size=128 | time=1.9093s
batch 64 | size=128 | time=1.7852s
batch 65 | size=128 | time=2.2991s
batch 66 | size=128 | time=2.3945s
batch 67 | size=128 | time=2.2464s
batch 68 | size=128 | time=2.1667s
batch 69 | size=128 | time=2.3387s
batch 70 | size=128 | time=2.2446s
batch 71 | size=128 | time=2.1006s
batch 72 | size=128 | time=2.2758s
batch 73 | size=128 | time=1.9492s
batch 74 | size=128 | time=2.2833s
batch 75 | size=128 | time=2.0939s
batch 76 | size=128 | time=2.4117s
batch 77 | size=128 | time=2.4003s
batch 78 | size=128 | time=2.2642s
batch 79 | size=128 | time=2.2067s
batch 80 | size=128 | time=2.3171s
batch 81 | size=128 | time=2.2782s
batch 82 | size=128 | time=2.3019s
batch 83 | size=128 | time=2.4707s
batch 84 | size=128 | time=2.1371s
batch 85 | size=128 | time=2.3188s
batch 86 | size=128 | time=2.5464s
batch 87 | size=128 | time=2.5471s
batch 88 | size=128 | time=2.2423s
batch 89 | size=128 | time=2.4761s
batch 90 | size=128 | time=2.4950s
batch 91 | size=128 | time=2.6103s
batch 92 | size=128 | time=2.6253s
batch 93 | size=128 | time=2.5077s
batch 94 | size=128 | time=2.5426s
batch 95 | size=128 | time=2.7473s
batch 96 | size=128 | time=2.7996s
batch 97 | size=128 | time=2.5709s
batch 98 | size=128 | time=2.8811s
batch 99 | size=128 | time=2.7836s
batch 100 | size=128 | time=3.1469s
batch 101 | size=128 | time=2.8381s
batch 102 | size=128 | time=3.0699s
batch 103 | size=128 | time=2.8106s
batch 104 | size=128 | time=2.9005s
batch 105 | size=128 | time=3.1215s
batch 106 | size=128 | time=3.3137s
batch 107 | size=128 | time=3.2879s
batch 108 | size=128 | time=3.5327s
batch 109 | size=128 | time=3.1880s
batch 110 | size=128 | time=3.6885s
batch 111 | size=128 | time=3.0307s
batch 112 | size=128 | time=2.9893s
batch 113 | size=128 | time=3.1747s
batch 114 | size=128 | time=3.6143s
batch 115 | size=128 | time=3.7983s
batch 116 | size=128 | time=3.5483s
batch 117 | size=128 | time=3.5834s
batch 118 | size=128 | time=3.4702s
batch 119 | size=128 | time=3.6284s
batch 120 | size=128 | time=3.6043s
batch 121 | size=128 | time=4.1111s
batch 122 | size=128 | time=4.0485s
batch 123 | size=128 | time=5.5847s
batch 124 | size=128 | time=4.3365s
batch 125 | size=128 | time=4.3575s
batch 126 | size=128 | time=5.1740s
batch 127 | size=128 | time=5.2347s
batch 128 | size=128 | time=4.7587s
batch 129 | size=128 | time=4.5738s
batch 130 | size=128 | time=4.7534s
batch 131 | size=128 | time=4.5503s
batch 132 | size=128 | time=5.4825s
batch 133 | size=128 | time=5.4315s
batch 134 | size=128 | time=5.0334s
batch 135 | size=128 | time=5.4866s
batch 136 | size=128 | time=6.4084s
batch 137 | size=128 | time=5.3651s
batch 138 | size=128 | time=6.1908s
batch 139 | size=128 | time=6.0733s
batch 140 | size=128 | time=5.9295s
batch 141 | size=128 | time=5.6807s
batch 142 | size=128 | time=6.6404s
batch 143 | size=128 | time=6.1302s
batch 144 | size=128 | time=6.0502s
batch 145 | size=128 | time=6.4763s
batch 146 | size=128 | time=6.5961s
batch 147 | size=128 | time=6.6672s
batch 148 | size=128 | time=6.6629s
batch 149 | size=128 | time=8.5510s
batch 150 | size=128 | time=7.6416s
batch 151 | size=128 | time=7.0708s
batch 152 | size=128 | time=7.9664s
batch 153 | size=128 | time=6.9942s
batch 154 | size=128 | time=7.5026s
batch 155 | size=128 | time=8.4258s
batch 156 | size=128 | time=9.0819s
batch 157 | size=128 | time=8.7462s
batch 158 | size=128 | time=8.8470s
batch 159 | size=128 | time=8.6537s
batch 160 | size=128 | time=10.0254s
batch 161 | size=128 | time=8.4946s
batch 162 | size=128 | time=8.8867s
batch 163 | size=128 | time=10.1580s
batch 164 | size=128 | time=9.1526s
batch 165 | size=128 | time=12.2226s
batch 166 | size=74 | time=6.9437s

--- summary ---
total embedding time: 546.29s
total docs: 21194
dimension: 1024
Run 1 time: 547.22 sec

Running indexing experiment 2/3...
batch 1 | size=128 | time=0.6390s
batch 2 | size=128 | time=0.6436s
batch 3 | size=128 | time=0.7297s
batch 4 | size=128 | time=0.8183s
batch 5 | size=128 | time=0.7969s
batch 6 | size=128 | time=0.9232s
batch 7 | size=128 | time=0.9224s
batch 8 | size=128 | time=0.8264s
batch 9 | size=128 | time=0.9071s
batch 10 | size=128 | time=0.9656s
batch 11 | size=128 | time=0.9369s
batch 12 | size=128 | time=1.0936s
batch 13 | size=128 | time=1.1408s
batch 14 | size=128 | time=1.3232s
batch 15 | size=128 | time=1.0994s
batch 16 | size=128 | time=1.0065s
batch 17 | size=128 | time=1.0191s
batch 18 | size=128 | time=1.0454s
batch 19 | size=128 | time=1.1747s
batch 20 | size=128 | time=1.1867s
batch 21 | size=128 | time=1.1311s
batch 22 | size=128 | time=1.2660s
batch 23 | size=128 | time=1.4603s
batch 24 | size=128 | time=1.2821s
batch 25 | size=128 | time=1.3656s
batch 26 | size=128 | time=1.3109s
batch 27 | size=128 | time=1.1582s
batch 28 | size=128 | time=1.1969s
batch 29 | size=128 | time=1.2526s
batch 30 | size=128 | time=1.1462s
batch 31 | size=128 | time=1.3638s
batch 32 | size=128 | time=1.3172s
batch 33 | size=128 | time=1.3222s
batch 34 | size=128 | time=1.3521s
batch 35 | size=128 | time=1.2441s
batch 36 | size=128 | time=1.4101s
batch 37 | size=128 | time=1.4083s
batch 38 | size=128 | time=1.3049s
batch 39 | size=128 | time=1.3160s
batch 40 | size=128 | time=1.3451s
batch 41 | size=128 | time=1.3139s
batch 42 | size=128 | time=1.4571s
batch 43 | size=128 | time=1.7694s
batch 44 | size=128 | time=1.4722s
batch 45 | size=128 | time=1.5304s
batch 46 | size=128 | time=1.3817s
batch 47 | size=128 | time=1.4617s
batch 48 | size=128 | time=1.5145s
batch 49 | size=128 | time=1.5208s
batch 50 | size=128 | time=1.8026s
batch 51 | size=128 | time=1.5751s
batch 52 | size=128 | time=1.5769s
batch 53 | size=128 | time=1.5944s
batch 54 | size=128 | time=1.8078s
batch 55 | size=128 | time=1.5166s
batch 56 | size=128 | time=2.0088s
batch 57 | size=128 | time=1.8096s
batch 58 | size=128 | time=1.9066s
batch 59 | size=128 | time=1.8033s
batch 60 | size=128 | time=1.6754s
batch 61 | size=128 | time=1.8628s
batch 62 | size=128 | time=1.8927s
batch 63 | size=128 | time=1.8603s
batch 64 | size=128 | time=1.6560s
batch 65 | size=128 | time=2.1864s
batch 66 | size=128 | time=2.0336s
batch 67 | size=128 | time=1.9668s
batch 68 | size=128 | time=2.0783s
batch 69 | size=128 | time=2.2179s
batch 70 | size=128 | time=2.1318s
batch 71 | size=128 | time=2.0436s
batch 72 | size=128 | time=2.1466s
batch 73 | size=128 | time=1.8675s
batch 74 | size=128 | time=2.2170s
batch 75 | size=128 | time=2.0884s
batch 76 | size=128 | time=2.3798s
batch 77 | size=128 | time=2.3658s
batch 78 | size=128 | time=2.3804s
batch 79 | size=128 | time=2.2084s
batch 80 | size=128 | time=2.3607s
batch 81 | size=128 | time=2.4185s
batch 82 | size=128 | time=2.5089s
batch 83 | size=128 | time=2.5168s
batch 84 | size=128 | time=2.1822s
batch 85 | size=128 | time=2.3434s
batch 86 | size=128 | time=2.5903s
batch 87 | size=128 | time=2.6250s
batch 88 | size=128 | time=2.2909s
batch 89 | size=128 | time=2.5284s
batch 90 | size=128 | time=2.5329s
batch 91 | size=128 | time=2.6256s
batch 92 | size=128 | time=2.6477s
batch 93 | size=128 | time=2.5915s
batch 94 | size=128 | time=2.5759s
batch 95 | size=128 | time=2.7719s
batch 96 | size=128 | time=2.7719s
batch 97 | size=128 | time=2.5809s
batch 98 | size=128 | time=2.8998s
batch 99 | size=128 | time=2.7748s
batch 100 | size=128 | time=3.1165s
batch 101 | size=128 | time=2.7676s
batch 102 | size=128 | time=3.0384s
batch 103 | size=128 | time=2.8233s
batch 104 | size=128 | time=2.8814s
batch 105 | size=128 | time=3.0907s
batch 106 | size=128 | time=3.2483s
batch 107 | size=128 | time=3.1913s
batch 108 | size=128 | time=3.3591s
batch 109 | size=128 | time=3.1546s
batch 110 | size=128 | time=3.2795s
batch 111 | size=128 | time=2.8907s
batch 112 | size=128 | time=3.0176s
batch 113 | size=128 | time=3.1726s
batch 114 | size=128 | time=3.6332s
batch 115 | size=128 | time=3.7649s
batch 116 | size=128 | time=3.6156s
batch 117 | size=128 | time=3.7533s
batch 118 | size=128 | time=3.5049s
batch 119 | size=128 | time=3.5909s
batch 120 | size=128 | time=3.8918s
batch 121 | size=128 | time=3.8093s
batch 122 | size=128 | time=3.9180s
batch 123 | size=128 | time=5.1679s
batch 124 | size=128 | time=4.3705s
batch 125 | size=128 | time=4.3554s
batch 126 | size=128 | time=4.7817s
batch 127 | size=128 | time=5.1811s
batch 128 | size=128 | time=4.6039s
batch 129 | size=128 | time=4.4375s
batch 130 | size=128 | time=4.7062s
batch 131 | size=128 | time=4.4962s
batch 132 | size=128 | time=5.0568s
batch 133 | size=128 | time=5.1650s
batch 134 | size=128 | time=5.0026s
batch 135 | size=128 | time=5.4808s
batch 136 | size=128 | time=6.6384s
batch 137 | size=128 | time=5.2047s
batch 138 | size=128 | time=5.8790s
batch 139 | size=128 | time=5.9679s
batch 140 | size=128 | time=5.8590s
batch 141 | size=128 | time=5.4611s
batch 142 | size=128 | time=5.8803s
batch 143 | size=128 | time=5.7575s
batch 144 | size=128 | time=5.9309s
batch 145 | size=128 | time=6.4739s
batch 146 | size=128 | time=6.5702s
batch 147 | size=128 | time=6.5344s
batch 148 | size=128 | time=6.6229s
batch 149 | size=128 | time=8.4189s
batch 150 | size=128 | time=7.6618s
batch 151 | size=128 | time=7.0664s
batch 152 | size=128 | time=8.0090s
batch 153 | size=128 | time=6.9437s
batch 154 | size=128 | time=7.3805s
batch 155 | size=128 | time=8.1188s
batch 156 | size=128 | time=8.9656s
batch 157 | size=128 | time=8.6647s
batch 158 | size=128 | time=8.7542s
batch 159 | size=128 | time=8.4824s
batch 160 | size=128 | time=9.7596s
batch 161 | size=128 | time=8.4606s
batch 162 | size=128 | time=8.8926s
batch 163 | size=128 | time=9.9265s
batch 164 | size=128 | time=9.2458s
batch 165 | size=128 | time=11.7187s
batch 166 | size=74 | time=6.6182s

--- summary ---
total embedding time: 539.56s
total docs: 21194
dimension: 1024
Run 2 time: 540.10 sec

Running indexing experiment 3/3...
batch 1 | size=128 | time=0.6255s
batch 2 | size=128 | time=0.6385s
batch 3 | size=128 | time=0.7250s
batch 4 | size=128 | time=0.8265s
batch 5 | size=128 | time=0.7854s
batch 6 | size=128 | time=0.9046s
batch 7 | size=128 | time=0.8807s
batch 8 | size=128 | time=0.7872s
batch 9 | size=128 | time=0.8871s
batch 10 | size=128 | time=0.9484s
batch 11 | size=128 | time=0.9179s
batch 12 | size=128 | time=1.0130s
batch 13 | size=128 | time=1.0546s
batch 14 | size=128 | time=1.2717s
batch 15 | size=128 | time=1.0854s
batch 16 | size=128 | time=0.9912s
batch 17 | size=128 | time=1.0263s
batch 18 | size=128 | time=1.0490s
batch 19 | size=128 | time=1.1804s
batch 20 | size=128 | time=1.1757s
batch 21 | size=128 | time=1.0764s
batch 22 | size=128 | time=1.0736s
batch 23 | size=128 | time=1.2836s
batch 24 | size=128 | time=1.1766s
batch 25 | size=128 | time=1.2895s
batch 26 | size=128 | time=1.2834s
batch 27 | size=128 | time=1.1127s
batch 28 | size=128 | time=1.1302s
batch 29 | size=128 | time=1.2398s
batch 30 | size=128 | time=1.1400s
batch 31 | size=128 | time=1.3257s
batch 32 | size=128 | time=1.2886s
batch 33 | size=128 | time=1.2715s
batch 34 | size=128 | time=1.2957s
batch 35 | size=128 | time=1.1887s
batch 36 | size=128 | time=1.3818s
batch 37 | size=128 | time=1.3933s
batch 38 | size=128 | time=1.2890s
batch 39 | size=128 | time=1.2930s
batch 40 | size=128 | time=1.3380s
batch 41 | size=128 | time=1.3177s
batch 42 | size=128 | time=1.4810s
batch 43 | size=128 | time=1.7759s
batch 44 | size=128 | time=1.4611s
batch 45 | size=128 | time=1.5179s
batch 46 | size=128 | time=1.3832s
batch 47 | size=128 | time=1.4737s
batch 48 | size=128 | time=1.5145s
batch 49 | size=128 | time=1.5524s
batch 50 | size=128 | time=1.8356s
batch 51 | size=128 | time=1.5945s
batch 52 | size=128 | time=1.5755s
batch 53 | size=128 | time=1.5737s
batch 54 | size=128 | time=1.7857s
batch 55 | size=128 | time=1.5172s
batch 56 | size=128 | time=2.0039s
batch 57 | size=128 | time=1.8078s
batch 58 | size=128 | time=1.9311s
batch 59 | size=128 | time=1.8077s
batch 60 | size=128 | time=1.6640s
batch 61 | size=128 | time=1.8392s
batch 62 | size=128 | time=1.8373s
batch 63 | size=128 | time=1.8582s
batch 64 | size=128 | time=1.6539s
batch 65 | size=128 | time=2.2165s
batch 66 | size=128 | time=2.0642s
batch 67 | size=128 | time=1.9669s
batch 68 | size=128 | time=2.0692s
batch 69 | size=128 | time=2.2093s
batch 70 | size=128 | time=2.1271s
batch 71 | size=128 | time=2.0473s
batch 72 | size=128 | time=2.1836s
batch 73 | size=128 | time=1.9179s
batch 74 | size=128 | time=2.2433s
batch 75 | size=128 | time=2.0734s
batch 76 | size=128 | time=2.3921s
batch 77 | size=128 | time=2.4023s
batch 78 | size=128 | time=2.2938s
batch 79 | size=128 | time=2.2114s
batch 80 | size=128 | time=2.3521s
batch 81 | size=128 | time=2.3187s
batch 82 | size=128 | time=2.3442s
batch 83 | size=128 | time=2.5073s
batch 84 | size=128 | time=2.2142s
batch 85 | size=128 | time=2.3740s
batch 86 | size=128 | time=2.5867s
batch 87 | size=128 | time=2.5913s
batch 88 | size=128 | time=2.2608s
batch 89 | size=128 | time=2.5185s
batch 90 | size=128 | time=2.5502s
batch 91 | size=128 | time=2.6392s
batch 92 | size=128 | time=2.6416s
batch 93 | size=128 | time=2.5206s
batch 94 | size=128 | time=2.5411s
batch 95 | size=128 | time=2.7415s
batch 96 | size=128 | time=2.7740s
batch 97 | size=128 | time=2.5411s
batch 98 | size=128 | time=2.8180s
batch 99 | size=128 | time=2.7797s
batch 100 | size=128 | time=3.0968s
batch 101 | size=128 | time=2.7948s
batch 102 | size=128 | time=3.0370s
batch 103 | size=128 | time=2.7690s
batch 104 | size=128 | time=2.8757s
batch 105 | size=128 | time=3.0975s
batch 106 | size=128 | time=3.3028s
batch 107 | size=128 | time=3.1662s
batch 108 | size=128 | time=3.3407s
batch 109 | size=128 | time=3.1768s
batch 110 | size=128 | time=3.3632s
batch 111 | size=128 | time=2.9163s
batch 112 | size=128 | time=3.0224s
batch 113 | size=128 | time=3.1998s
batch 114 | size=128 | time=3.7103s
batch 115 | size=128 | time=3.7792s
batch 116 | size=128 | time=3.5705s
batch 117 | size=128 | time=3.5977s
batch 118 | size=128 | time=3.5445s
batch 119 | size=128 | time=3.5907s
batch 120 | size=128 | time=3.5921s
batch 121 | size=128 | time=3.7972s
batch 122 | size=128 | time=3.9498s
batch 123 | size=128 | time=5.1390s
batch 124 | size=128 | time=4.3280s
batch 125 | size=128 | time=4.3567s
batch 126 | size=128 | time=4.7622s
batch 127 | size=128 | time=5.1587s
batch 128 | size=128 | time=4.6126s
batch 129 | size=128 | time=4.4286s
batch 130 | size=128 | time=4.6865s
batch 131 | size=128 | time=4.5946s
batch 132 | size=128 | time=5.0782s
batch 133 | size=128 | time=5.1826s
batch 134 | size=128 | time=5.0450s
batch 135 | size=128 | time=5.4239s
batch 136 | size=128 | time=6.4248s
batch 137 | size=128 | time=5.1982s
batch 138 | size=128 | time=5.8581s
batch 139 | size=128 | time=6.0597s
batch 140 | size=128 | time=5.7665s
batch 141 | size=128 | time=5.5163s
batch 142 | size=128 | time=5.8888s
batch 143 | size=128 | time=5.8026s
batch 144 | size=128 | time=5.9596s
batch 145 | size=128 | time=6.4038s
batch 146 | size=128 | time=6.6615s
batch 147 | size=128 | time=6.4876s
batch 148 | size=128 | time=6.7247s
batch 149 | size=128 | time=8.3206s
batch 150 | size=128 | time=7.7307s
batch 151 | size=128 | time=6.9875s
batch 152 | size=128 | time=8.0605s
batch 153 | size=128 | time=6.9552s
batch 154 | size=128 | time=7.4016s
batch 155 | size=128 | time=8.1593s
batch 156 | size=128 | time=8.9806s
batch 157 | size=128 | time=8.7836s
batch 158 | size=128 | time=8.6676s
batch 159 | size=128 | time=8.5019s
batch 160 | size=128 | time=9.7784s
batch 161 | size=128 | time=8.3890s
batch 162 | size=128 | time=8.9871s
batch 163 | size=128 | time=9.8936s
batch 164 | size=128 | time=9.1188s
batch 165 | size=128 | time=11.8866s
batch 166 | size=74 | time=6.7127s

--- summary ---
total embedding time: 537.60s
total docs: 21194
dimension: 1024
Run 3 time: 538.00 sec

============== INDEXING STATS ==============
Documents embedded      : 21194
Runs                    : 3
Individual times        : [547.2184402089999, 540.0959588249999, 538.0027371440001]
Average indexing time   : 541.77 sec
Avg time per document   : 0.025563 sec
Throughput              : 39.12 docs/sec
============================================

In [ ]:
import time
import numpy as np


def measure_dense_retrieval_latency(
    index,
    queries,
    embedding_model,
    top_k=100,
    warmup=True,
    runs=3
):
    """
    Measure end-to-end dense retrieval latency:
    text query -> embedding -> FAISS search
    """

    num_queries = len(queries)

    # Warm-up
    if warmup:
        emb = embed_query(
            queries[0],
        )
        index.search(emb, top_k)

    times = []

    for _ in tqdm(range(runs)):

        start = time.perf_counter()

        for query in queries:

            # Query embedding
            query_embedding = embed_query(
                query,
            )

            # Retrieval
            index.search(query_embedding, top_k)

        end = time.perf_counter()

        times.append(end - start)


    avg_time = np.mean(times)

    return {
        "num_queries": num_queries,
        "top_k": top_k,
        "runs": runs,
        "total_time_sec": avg_time,
        "avg_latency_per_query_ms": (avg_time / num_queries) * 1000,
        "queries_per_second": num_queries / avg_time,
        "all_runs": times
    }

#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=3
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

100%|██████████| 3/3 [22:51<00:00, 457.09s/it]

============== RETRIEVAL STATS ==============
Total queries           : 5731
Top-k                   : 100
Runs                    : 3
Total time              : 457.08 sec
Avg latency per query   : 79.76 ms
Throughput              : 12.54 queries/sec
============================================

In [ ]:
import os

def get_index_size(index_path):
    """
    Returns FAISS index size in MB/GB.
    """
    size_bytes = os.path.getsize(index_path)

    return {
        "size_bytes": size_bytes,
        "size_MB": size_bytes / (1024 ** 2),
        "size_GB": size_bytes / (1024 ** 3)
    }

index_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bge-m3/sa_faiss.index"

index_size = get_index_size(index_file)

print(f"Index size: {index_size['size_MB']:.2f} MB")
print(f"Index size: {index_size['size_GB']:.3f} GB")

Index size: 87.38 MB
Index size: 0.085 GB

#### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.2630  0.0966     NaN      NaN
1   10  0.3192  0.0650  0.2088   0.2293
2  100  0.5155  0.0118     NaN      NaN

### b. e5-large

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('intfloat/multilingual-e5-large')

In [ ]:
def embed_texts(batch_texts, model):
    """
    BGE-M3 HF embedding (dense only)
    """
    return model.encode(batch_texts)

def build_faiss_pipeline(
    texts,
    ids,
    model,
    batch_size=32,
    save_path=None
):
    all_embeddings = []
    total_time = 0.0

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        start = time.time()

        emb = embed_texts(batch, model)

        end = time.time()
        total_time += (end - start)

        print(f"batch {i//batch_size + 1} | size={len(batch)} | time={end-start:.4f}s")

        all_embeddings.append(emb)

    embeddings = np.concatenate(all_embeddings, axis=0).astype("float32")

    dim = np.array(embeddings).shape[1]
    index = faiss.IndexFlatIP(dim)
    index = faiss.IndexIDMap(index)
    index.add_with_ids(embeddings, ids)

    # --- SAVE ARTIFACTS ---
    if save_path:
        os.makedirs(save_path, exist_ok=True)

        # 1. save faiss index
        faiss.write_index(index, os.path.join(save_path, "sa_faiss.index"))

        # 2. save embeddings
        np.save(os.path.join(save_path, "sa_embeddings.npy"), embeddings)

    print("\n--- summary ---")
    print(f"total embedding time: {total_time:.2f}s")
    print(f"total docs: {len(ids)}")
    print(f"dimension: {dim}")

    return index,embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

index, embeddings = build_faiss_pipeline(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

Loading documents...
Total documents: 22326
batch 1 | size=128 | time=0.8386s
batch 2 | size=128 | time=0.9213s
batch 3 | size=128 | time=1.0383s
batch 4 | size=128 | time=1.0420s
batch 5 | size=128 | time=1.1159s
batch 6 | size=128 | time=1.1429s
batch 7 | size=128 | time=1.1948s
batch 8 | size=128 | time=1.4711s
batch 9 | size=128 | time=1.8364s
batch 10 | size=128 | time=2.1579s
batch 11 | size=128 | time=2.2954s
batch 12 | size=128 | time=1.6781s
batch 13 | size=128 | time=1.6832s
batch 14 | size=128 | time=1.4776s
batch 15 | size=128 | time=1.4434s
batch 16 | size=128 | time=1.4011s
batch 17 | size=128 | time=1.4410s
batch 18 | size=128 | time=1.4023s
batch 19 | size=128 | time=1.4672s
batch 20 | size=128 | time=1.4502s
batch 21 | size=128 | time=1.4685s
batch 22 | size=128 | time=1.4430s
batch 23 | size=128 | time=1.3688s
batch 24 | size=128 | time=1.4559s
batch 25 | size=128 | time=1.4369s
batch 26 | size=128 | time=1.4821s
batch 27 | size=128 | time=1.3772s
batch 28 | size=128 | time=1.4904s
batch 29 | size=128 | time=1.4689s
batch 30 | size=128 | time=1.4012s
batch 31 | size=128 | time=1.4487s
batch 32 | size=128 | time=1.4710s
batch 33 | size=128 | time=1.3731s
batch 34 | size=128 | time=1.4492s
batch 35 | size=128 | time=1.3769s
batch 36 | size=128 | time=1.3748s
batch 37 | size=128 | time=1.4765s
batch 38 | size=128 | time=1.5840s
batch 39 | size=128 | time=1.4543s
batch 40 | size=128 | time=1.5146s
batch 41 | size=128 | time=1.5836s
batch 42 | size=128 | time=1.6174s
batch 43 | size=128 | time=1.3368s
batch 44 | size=128 | time=1.7105s
batch 45 | size=128 | time=1.7283s
batch 46 | size=128 | time=1.7451s
batch 47 | size=128 | time=1.7207s
batch 48 | size=128 | time=1.7512s
batch 49 | size=128 | time=1.7923s
batch 50 | size=128 | time=1.8232s
batch 51 | size=128 | time=1.8109s
batch 52 | size=128 | time=1.9166s
batch 53 | size=128 | time=1.8536s
batch 54 | size=128 | time=1.9503s
batch 55 | size=128 | time=1.9490s
batch 56 | size=128 | time=2.0362s
batch 57 | size=128 | time=2.0370s
batch 58 | size=128 | time=2.0790s
batch 59 | size=128 | time=2.1455s
batch 60 | size=128 | time=2.2785s
batch 61 | size=128 | time=2.0779s
batch 62 | size=128 | time=2.1693s
batch 63 | size=128 | time=2.2926s
batch 64 | size=128 | time=2.1318s
batch 65 | size=128 | time=2.1243s
batch 66 | size=128 | time=2.2622s
batch 67 | size=128 | time=2.1911s
batch 68 | size=128 | time=2.1103s
batch 69 | size=128 | time=2.1067s
batch 70 | size=128 | time=2.2086s
batch 71 | size=128 | time=2.1728s
batch 72 | size=128 | time=2.1328s
batch 73 | size=128 | time=2.1700s
batch 74 | size=128 | time=2.2966s
batch 75 | size=128 | time=2.0324s
batch 76 | size=128 | time=2.2333s
batch 77 | size=128 | time=2.2217s
batch 78 | size=128 | time=2.2485s
batch 79 | size=128 | time=2.2566s
batch 80 | size=128 | time=2.4653s
batch 81 | size=128 | time=2.6888s
batch 82 | size=128 | time=2.4378s
batch 83 | size=128 | time=2.2136s
batch 84 | size=128 | time=2.5049s
batch 85 | size=128 | time=2.5498s
batch 86 | size=128 | time=2.4813s
batch 87 | size=128 | time=2.7575s
batch 88 | size=128 | time=2.6225s
batch 89 | size=128 | time=2.5777s
batch 90 | size=128 | time=2.7489s
batch 91 | size=128 | time=2.8017s
batch 92 | size=128 | time=2.9368s
batch 93 | size=128 | time=2.6582s
batch 94 | size=128 | time=2.7040s
batch 95 | size=128 | time=2.6133s
batch 96 | size=128 | time=2.9209s
batch 97 | size=128 | time=2.9069s
batch 98 | size=128 | time=2.9550s
batch 99 | size=128 | time=2.9361s
batch 100 | size=128 | time=2.9673s
batch 101 | size=128 | time=3.1313s
batch 102 | size=128 | time=3.0722s
batch 103 | size=128 | time=3.0813s
batch 104 | size=128 | time=2.9798s
batch 105 | size=128 | time=3.4089s
batch 106 | size=128 | time=2.9163s
batch 107 | size=128 | time=3.1793s
batch 108 | size=128 | time=3.1173s
batch 109 | size=128 | time=3.0880s
batch 110 | size=128 | time=3.3445s
batch 111 | size=128 | time=3.0878s
batch 112 | size=128 | time=3.4667s
batch 113 | size=128 | time=3.5631s
batch 114 | size=128 | time=3.5932s
batch 115 | size=128 | time=3.8009s
batch 116 | size=128 | time=3.6862s
batch 117 | size=128 | time=3.4799s
batch 118 | size=128 | time=3.5881s
batch 119 | size=128 | time=3.5349s
batch 120 | size=128 | time=3.7069s
batch 121 | size=128 | time=4.0555s
batch 122 | size=128 | time=4.1969s
batch 123 | size=128 | time=4.0341s
batch 124 | size=128 | time=4.4616s
batch 125 | size=128 | time=4.3682s
batch 126 | size=128 | time=4.1916s
batch 127 | size=128 | time=4.3427s
batch 128 | size=128 | time=4.4836s
batch 129 | size=128 | time=4.3252s
batch 130 | size=128 | time=5.0403s
batch 131 | size=128 | time=4.6018s
batch 132 | size=128 | time=4.5601s
batch 133 | size=128 | time=5.0850s
batch 134 | size=128 | time=4.9076s
batch 135 | size=128 | time=4.6324s
batch 136 | size=128 | time=5.0212s
batch 137 | size=128 | time=5.1231s
batch 138 | size=128 | time=5.1230s
batch 139 | size=128 | time=5.3204s
batch 140 | size=128 | time=5.7305s
batch 141 | size=128 | time=5.2467s
batch 142 | size=128 | time=5.8731s
batch 143 | size=128 | time=6.2371s
batch 144 | size=128 | time=6.0239s
batch 145 | size=128 | time=6.1730s
batch 146 | size=128 | time=6.4800s
batch 147 | size=128 | time=6.0819s
batch 148 | size=128 | time=6.1094s
batch 149 | size=128 | time=6.3241s
batch 150 | size=128 | time=6.6181s
batch 151 | size=128 | time=6.6121s
batch 152 | size=128 | time=6.5330s
batch 153 | size=128 | time=7.3478s
batch 154 | size=128 | time=7.0397s
batch 155 | size=128 | time=7.4399s
batch 156 | size=128 | time=7.3125s
batch 157 | size=128 | time=8.2149s
batch 158 | size=128 | time=8.1412s
batch 159 | size=128 | time=8.0222s
batch 160 | size=128 | time=8.6365s
batch 161 | size=128 | time=7.9208s
batch 162 | size=128 | time=8.3622s
batch 163 | size=128 | time=9.1996s
batch 164 | size=128 | time=8.8876s
batch 165 | size=128 | time=9.8224s
batch 166 | size=128 | time=9.2186s
batch 167 | size=128 | time=9.8848s
batch 168 | size=128 | time=10.1252s
batch 169 | size=128 | time=10.0958s
batch 170 | size=128 | time=10.6691s
batch 171 | size=128 | time=11.3426s
batch 172 | size=128 | time=11.2530s
batch 173 | size=128 | time=10.7196s
batch 174 | size=128 | time=11.3157s
batch 175 | size=54 | time=5.3791s

--- summary ---
total embedding time: 633.26s
total docs: 22326
dimension: 1024

================ INDEXING STATS ================
Total documents embedded : 22326
Total indexing time      : 642.37 sec
Average time per doc     : 0.028772 sec
Throughput              : 34.76 docs/sec
=================================================

In [ ]:
#embed queries
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/queries_embed.jsonl"

os.makedirs(os.path.dirname(query_output_file), exist_ok=True)

batch_items = []
batch_texts = []

start_time = time.time()   #

with open(query_output_file, "w", encoding="utf-8") as out_f:
    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)
            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)

            # ---- RUN BATCH ----
            if len(batch_texts) == BATCH_SIZE:

                embeddings = embed_texts(batch_texts, model)

                for it, emb in zip(batch_items, embeddings):
                    to_write = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "embedding": emb.tolist(),
                        "gold": it["relevant_subarticles"]
                    }
                    out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

                batch_items = []
                batch_texts = []

        # ---- FLUSH REMAINING ----
        if batch_texts:
            embeddings = embed_texts(batch_texts, model)

            for it, emb in zip(batch_items, embeddings):
                to_write = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "embedding": emb.tolist(),
                    "gold": it["relevant_subarticles"]
                }
                out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

end_time = time.time()   # END TIMER

print("Done! Query embeddings written to:", query_output_file)

# FINAL STATS
total_time = end_time - start_time
print(f"\nTotal embedding time: {total_time:.2f} seconds")
print(f"Average time per query: {total_time / sum(1 for _ in open(query_file)):.4f} sec")

Embedding queries: 5731it [06:31, 14.65it/s]

Done! Query embeddings written to: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/queries_embed.jsonl

Total embedding time: 398.23 seconds
Average time per query: 0.0695 sec

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))


query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/queries_embed.jsonl"

all_query_embeddings = []
all_gold_labels = []

print(f"Loading all embeddings from: {query_output_file}")

with open(query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        all_query_embeddings.append(item["embedding"])
        all_gold_labels.append(item["gold"])

# Convert to numpy matrix
query_matrix = np.array(all_query_embeddings).astype("float32")

print(f"Performing batch search for {len(query_matrix)} queries...")

# START TIMER (RETRIEVAL TIME ONLY)
start_time = time.time()

D, I = index.search(query_matrix, 100)

end_time = time.time()

# RETRIEVAL TIME METRICS
retrieval_time = end_time - start_time
num_queries = len(query_matrix)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries           : {num_queries}")
print(f"Total retrieval time    : {retrieval_time:.4f} sec")
print(f"Avg time per query      : {retrieval_time / num_queries:.6f} sec")
print(f"Throughput             : {num_queries / retrieval_time:.2f} queries/sec")
print("=================================================\n")

# FORMAT RESULTS FOR EVALUATION
all_results_for_metrics = []

for row_idx in range(len(I)):
    retrieved_ids = I[row_idx].tolist()
    all_results_for_metrics.append((retrieved_ids, all_gold_labels[row_idx]))

print("Batch retrieval complete.")

Loading all embeddings from: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/queries_embed.jsonl
Performing batch search for 5731 queries...

================ RETRIEVAL STATS ================
Total queries           : 5731
Total retrieval time    : 4.9031 sec
Avg time per query      : 0.000856 sec
Throughput             : 1168.85 queries/sec
=================================================

Batch retrieval complete.

#### Efficiency

In [ ]:
def measure_indexing_time(
    texts,
    ids,
    model,
    batch_size,
    save_path="/content/",
    runs=3
):
    """
    Measure dense indexing time over multiple runs.
    """

    num_docs = len(texts)

    # Warmup
    _ = embed_texts(
        texts[:min(batch_size, num_docs)],
        model
    )

    times = []

    for run in range(runs):
        print(f"\nRunning indexing experiment {run+1}/{runs}...")

        start_time = time.perf_counter()

        index, embeddings = build_faiss_pipeline(
            texts=texts,
            ids=ids,
            model=model,
            batch_size=batch_size,
            save_path=save_path
        )

        end_time = time.perf_counter()

        elapsed = end_time - start_time
        times.append(elapsed)

        print(f"Run {run+1} time: {elapsed:.2f} sec")


    avg_indexing_time = np.mean(times)

    results = {
        "num_documents": num_docs,
        "runs": runs,
        "all_times": times,
        "avg_indexing_time_sec": avg_indexing_time,
        "avg_time_per_document_sec": avg_indexing_time / num_docs,
        "throughput_docs_per_sec": num_docs / avg_indexing_time
    }

    return results

indexing_stats = measure_indexing_time(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path="/content/",
    runs=3
)

print("\n============== INDEXING STATS ==============")
print(f"Documents embedded      : {indexing_stats['num_documents']}")
print(f"Runs                    : {indexing_stats['runs']}")
print(f"Individual times        : {indexing_stats['all_times']}")
print(f"Average indexing time   : {indexing_stats['avg_indexing_time_sec']:.2f} sec")
print(f"Avg time per document   : {indexing_stats['avg_time_per_document_sec']:.6f} sec")
print(f"Throughput              : {indexing_stats['throughput_docs_per_sec']:.2f} docs/sec")
print("============================================")

Running indexing experiment 1/3...
batch 1 | size=128 | time=0.5922s
batch 2 | size=128 | time=0.6868s
batch 3 | size=128 | time=0.7700s
batch 4 | size=128 | time=0.8075s
batch 5 | size=128 | time=0.8073s
batch 6 | size=128 | time=0.8514s
batch 7 | size=128 | time=0.8597s
batch 8 | size=128 | time=0.8110s
batch 9 | size=128 | time=0.8741s
batch 10 | size=128 | time=0.9184s
batch 11 | size=128 | time=0.9925s
batch 12 | size=128 | time=1.0309s
batch 13 | size=128 | time=1.0164s
batch 14 | size=128 | time=1.0708s
batch 15 | size=128 | time=1.0468s
batch 16 | size=128 | time=1.0686s
batch 17 | size=128 | time=1.0378s
batch 18 | size=128 | time=1.1299s
batch 19 | size=128 | time=1.1950s
batch 20 | size=128 | time=1.1967s
batch 21 | size=128 | time=1.1466s
batch 22 | size=128 | time=1.1630s
batch 23 | size=128 | time=1.2201s
batch 24 | size=128 | time=1.2464s
batch 25 | size=128 | time=1.2768s
batch 26 | size=128 | time=1.2226s
batch 27 | size=128 | time=1.2987s
batch 28 | size=128 | time=1.3213s
batch 29 | size=128 | time=1.2932s
batch 30 | size=128 | time=1.3140s
batch 31 | size=128 | time=1.3333s
batch 32 | size=128 | time=1.2530s
batch 33 | size=128 | time=1.3584s
batch 34 | size=128 | time=1.3153s
batch 35 | size=128 | time=1.3455s
batch 36 | size=128 | time=1.5119s
batch 37 | size=128 | time=1.5426s
batch 38 | size=128 | time=1.4365s
batch 39 | size=128 | time=1.4627s
batch 40 | size=128 | time=1.4374s
batch 41 | size=128 | time=1.3611s
batch 42 | size=128 | time=1.5624s
batch 43 | size=128 | time=1.6899s
batch 44 | size=128 | time=1.6726s
batch 45 | size=128 | time=1.5286s
batch 46 | size=128 | time=1.5954s
batch 47 | size=128 | time=1.6811s
batch 48 | size=128 | time=1.6617s
batch 49 | size=128 | time=1.6898s
batch 50 | size=128 | time=1.7271s
batch 51 | size=128 | time=1.6221s
batch 52 | size=128 | time=1.7833s
batch 53 | size=128 | time=1.7813s
batch 54 | size=128 | time=1.6999s
batch 55 | size=128 | time=1.7131s
batch 56 | size=128 | time=1.7462s
batch 57 | size=128 | time=1.7875s
batch 58 | size=128 | time=1.7905s
batch 59 | size=128 | time=1.7341s
batch 60 | size=128 | time=1.8310s
batch 61 | size=128 | time=1.7841s
batch 62 | size=128 | time=1.8102s
batch 63 | size=128 | time=1.9541s
batch 64 | size=128 | time=1.7660s
batch 65 | size=128 | time=1.7937s
batch 66 | size=128 | time=1.8721s
batch 67 | size=128 | time=1.9039s
batch 68 | size=128 | time=1.8455s
batch 69 | size=128 | time=2.0384s
batch 70 | size=128 | time=1.8834s
batch 71 | size=128 | time=1.8233s
batch 72 | size=128 | time=1.9698s
batch 73 | size=128 | time=1.9795s
batch 74 | size=128 | time=2.1341s
batch 75 | size=128 | time=2.0406s
batch 76 | size=128 | time=2.1675s
batch 77 | size=128 | time=2.2022s
batch 78 | size=128 | time=2.1188s
batch 79 | size=128 | time=2.1285s
batch 80 | size=128 | time=2.2122s
batch 81 | size=128 | time=2.2276s
batch 82 | size=128 | time=2.2804s
batch 83 | size=128 | time=2.2836s
batch 84 | size=128 | time=2.1484s
batch 85 | size=128 | time=2.3993s
batch 86 | size=128 | time=2.4904s
batch 87 | size=128 | time=2.4338s
batch 88 | size=128 | time=2.2454s
batch 89 | size=128 | time=2.4784s
batch 90 | size=128 | time=2.4709s
batch 91 | size=128 | time=2.4533s
batch 92 | size=128 | time=2.6257s
batch 93 | size=128 | time=2.5656s
batch 94 | size=128 | time=2.3334s
batch 95 | size=128 | time=2.7030s
batch 96 | size=128 | time=2.8262s
batch 97 | size=128 | time=2.4575s
batch 98 | size=128 | time=2.7864s
batch 99 | size=128 | time=2.8856s
batch 100 | size=128 | time=2.7609s
batch 101 | size=128 | time=2.5451s
batch 102 | size=128 | time=2.8564s
batch 103 | size=128 | time=2.7136s
batch 104 | size=128 | time=2.7728s
batch 105 | size=128 | time=2.7389s
batch 106 | size=128 | time=3.2591s
batch 107 | size=128 | time=3.0043s
batch 108 | size=128 | time=3.2701s
batch 109 | size=128 | time=3.2692s
batch 110 | size=128 | time=3.2571s
batch 111 | size=128 | time=3.0376s
batch 112 | size=128 | time=3.0527s
batch 113 | size=128 | time=3.3300s
batch 114 | size=128 | time=3.3781s
batch 115 | size=128 | time=3.6418s
batch 116 | size=128 | time=3.4805s
batch 117 | size=128 | time=3.6109s
batch 118 | size=128 | time=3.7486s
batch 119 | size=128 | time=3.4940s
batch 120 | size=128 | time=3.7630s
batch 121 | size=128 | time=3.7700s
batch 122 | size=128 | time=3.8064s
batch 123 | size=128 | time=4.0616s
batch 124 | size=128 | time=3.9510s
batch 125 | size=128 | time=4.0908s
batch 126 | size=128 | time=4.3579s
batch 127 | size=128 | time=4.4880s
batch 128 | size=128 | time=4.2325s
batch 129 | size=128 | time=4.3893s
batch 130 | size=128 | time=4.3545s
batch 131 | size=128 | time=4.4806s
batch 132 | size=128 | time=4.7609s
batch 133 | size=128 | time=5.0391s
batch 134 | size=128 | time=4.8656s
batch 135 | size=128 | time=5.0242s
batch 136 | size=128 | time=5.5944s
batch 137 | size=128 | time=5.3311s
batch 138 | size=128 | time=5.4896s
batch 139 | size=128 | time=5.7657s
batch 140 | size=128 | time=5.4456s
batch 141 | size=128 | time=5.4014s
batch 142 | size=128 | time=5.9138s
batch 143 | size=128 | time=5.5226s
batch 144 | size=128 | time=5.6429s
batch 145 | size=128 | time=6.3330s
batch 146 | size=128 | time=6.2097s
batch 147 | size=128 | time=6.4710s
batch 148 | size=128 | time=6.3681s
batch 149 | size=128 | time=7.4877s
batch 150 | size=128 | time=7.0622s
batch 151 | size=128 | time=7.0963s
batch 152 | size=128 | time=7.3041s
batch 153 | size=128 | time=7.2298s
batch 154 | size=128 | time=7.4367s
batch 155 | size=128 | time=7.5994s
batch 156 | size=128 | time=8.0806s
batch 157 | size=128 | time=7.8810s
batch 158 | size=128 | time=8.1402s
batch 159 | size=128 | time=8.5127s
batch 160 | size=128 | time=9.3091s
batch 161 | size=128 | time=9.0367s
batch 162 | size=128 | time=9.2987s
batch 163 | size=128 | time=9.6407s
batch 164 | size=128 | time=9.2797s
batch 165 | size=128 | time=10.0533s
batch 166 | size=74 | time=6.4787s

--- summary ---
total embedding time: 520.52s
total docs: 21194
dimension: 1024
Run 1 time: 521.16 sec

Running indexing experiment 2/3...
batch 1 | size=128 | time=0.6293s
batch 2 | size=128 | time=0.7347s
batch 3 | size=128 | time=0.8249s
batch 4 | size=128 | time=0.8474s
batch 5 | size=128 | time=0.8697s
batch 6 | size=128 | time=0.9064s
batch 7 | size=128 | time=0.9149s
batch 8 | size=128 | time=0.8607s
batch 9 | size=128 | time=0.9042s
batch 10 | size=128 | time=0.9638s
batch 11 | size=128 | time=1.0300s
batch 12 | size=128 | time=1.0920s
batch 13 | size=128 | time=1.0648s
batch 14 | size=128 | time=1.1278s
batch 15 | size=128 | time=1.1000s
batch 16 | size=128 | time=1.1207s
batch 17 | size=128 | time=1.0952s
batch 18 | size=128 | time=1.1825s
batch 19 | size=128 | time=1.2677s
batch 20 | size=128 | time=1.2570s
batch 21 | size=128 | time=1.2029s
batch 22 | size=128 | time=1.2112s
batch 23 | size=128 | time=1.2244s
batch 24 | size=128 | time=1.2683s
batch 25 | size=128 | time=1.2907s
batch 26 | size=128 | time=1.2476s
batch 27 | size=128 | time=1.3107s
batch 28 | size=128 | time=1.3323s
batch 29 | size=128 | time=1.3001s
batch 30 | size=128 | time=1.3248s
batch 31 | size=128 | time=1.3551s
batch 32 | size=128 | time=1.2685s
batch 33 | size=128 | time=1.3549s
batch 34 | size=128 | time=1.2821s
batch 35 | size=128 | time=1.3152s
batch 36 | size=128 | time=1.4749s
batch 37 | size=128 | time=1.5185s
batch 38 | size=128 | time=1.3973s
batch 39 | size=128 | time=1.4312s
batch 40 | size=128 | time=1.4103s
batch 41 | size=128 | time=1.3434s
batch 42 | size=128 | time=1.5397s
batch 43 | size=128 | time=1.6424s
batch 44 | size=128 | time=1.5963s
batch 45 | size=128 | time=1.4594s
batch 46 | size=128 | time=1.5412s
batch 47 | size=128 | time=1.6313s
batch 48 | size=128 | time=1.6094s
batch 49 | size=128 | time=1.6513s
batch 50 | size=128 | time=1.7093s
batch 51 | size=128 | time=1.6019s
batch 52 | size=128 | time=1.7303s
batch 53 | size=128 | time=1.7171s
batch 54 | size=128 | time=1.6727s
batch 55 | size=128 | time=1.6898s
batch 56 | size=128 | time=1.7345s
batch 57 | size=128 | time=1.7620s
batch 58 | size=128 | time=1.8062s
batch 59 | size=128 | time=1.7570s
batch 60 | size=128 | time=1.8193s
batch 61 | size=128 | time=1.7656s
batch 62 | size=128 | time=1.8122s
batch 63 | size=128 | time=1.9635s
batch 64 | size=128 | time=1.7731s
batch 65 | size=128 | time=1.8101s
batch 66 | size=128 | time=1.8977s
batch 67 | size=128 | time=1.9230s
batch 68 | size=128 | time=1.8334s
batch 69 | size=128 | time=2.0422s
batch 70 | size=128 | time=1.9019s
batch 71 | size=128 | time=1.8396s
batch 72 | size=128 | time=1.9823s
batch 73 | size=128 | time=2.0450s
batch 74 | size=128 | time=2.1764s
batch 75 | size=128 | time=2.0121s
batch 76 | size=128 | time=2.1795s
batch 77 | size=128 | time=2.2356s
batch 78 | size=128 | time=2.1316s
batch 79 | size=128 | time=2.1634s
batch 80 | size=128 | time=2.2596s
batch 81 | size=128 | time=2.2392s
batch 82 | size=128 | time=2.2692s
batch 83 | size=128 | time=2.2855s
batch 84 | size=128 | time=2.1515s
batch 85 | size=128 | time=2.3926s
batch 86 | size=128 | time=2.5243s
batch 87 | size=128 | time=2.4309s
batch 88 | size=128 | time=2.1901s
batch 89 | size=128 | time=2.4608s
batch 90 | size=128 | time=2.4502s
batch 91 | size=128 | time=2.4482s
batch 92 | size=128 | time=2.6514s
batch 93 | size=128 | time=2.5301s
batch 94 | size=128 | time=2.3077s
batch 95 | size=128 | time=2.6946s
batch 96 | size=128 | time=2.8196s
batch 97 | size=128 | time=2.4814s
batch 98 | size=128 | time=2.7811s
batch 99 | size=128 | time=2.8580s
batch 100 | size=128 | time=2.7593s
batch 101 | size=128 | time=2.5397s
batch 102 | size=128 | time=2.8829s
batch 103 | size=128 | time=2.7378s
batch 104 | size=128 | time=2.7647s
batch 105 | size=128 | time=2.7490s
batch 106 | size=128 | time=3.2877s
batch 107 | size=128 | time=3.0434s
batch 108 | size=128 | time=3.2870s
batch 109 | size=128 | time=3.2664s
batch 110 | size=128 | time=3.2737s
batch 111 | size=128 | time=3.0525s
batch 112 | size=128 | time=3.0768s
batch 113 | size=128 | time=3.2911s
batch 114 | size=128 | time=3.3890s
batch 115 | size=128 | time=3.6562s
batch 116 | size=128 | time=3.5314s
batch 117 | size=128 | time=3.5533s
batch 118 | size=128 | time=3.7449s
batch 119 | size=128 | time=3.5020s
batch 120 | size=128 | time=3.7605s
batch 121 | size=128 | time=3.7212s
batch 122 | size=128 | time=3.8151s
batch 123 | size=128 | time=4.0986s
batch 124 | size=128 | time=3.9353s
batch 125 | size=128 | time=4.0625s
batch 126 | size=128 | time=4.3733s
batch 127 | size=128 | time=4.5009s
batch 128 | size=128 | time=4.2141s
batch 129 | size=128 | time=4.3971s
batch 130 | size=128 | time=4.4183s
batch 131 | size=128 | time=4.4252s
batch 132 | size=128 | time=4.7567s
batch 133 | size=128 | time=5.0757s
batch 134 | size=128 | time=4.8335s
batch 135 | size=128 | time=5.0240s
batch 136 | size=128 | time=5.5824s
batch 137 | size=128 | time=5.2447s
batch 138 | size=128 | time=5.5154s
batch 139 | size=128 | time=5.7159s
batch 140 | size=128 | time=5.4420s
batch 141 | size=128 | time=5.4568s
batch 142 | size=128 | time=5.8750s
batch 143 | size=128 | time=5.5669s
batch 144 | size=128 | time=5.6158s
batch 145 | size=128 | time=6.3532s
batch 146 | size=128 | time=6.2164s
batch 147 | size=128 | time=6.4558s
batch 148 | size=128 | time=6.4100s
batch 149 | size=128 | time=7.4286s
batch 150 | size=128 | time=7.0829s
batch 151 | size=128 | time=7.0652s
batch 152 | size=128 | time=7.3113s
batch 153 | size=128 | time=7.1877s
batch 154 | size=128 | time=7.4452s
batch 155 | size=128 | time=7.5867s
batch 156 | size=128 | time=8.0994s
batch 157 | size=128 | time=7.9381s
batch 158 | size=128 | time=8.1119s
batch 159 | size=128 | time=8.5364s
batch 160 | size=128 | time=9.2506s
batch 161 | size=128 | time=8.9963s
batch 162 | size=128 | time=9.2991s
batch 163 | size=128 | time=9.6354s
batch 164 | size=128 | time=9.2688s
batch 165 | size=128 | time=10.0485s
batch 166 | size=74 | time=6.4133s

--- summary ---
total embedding time: 521.00s
total docs: 21194
dimension: 1024
Run 2 time: 528.46 sec

Running indexing experiment 3/3...
batch 1 | size=128 | time=0.6914s
batch 2 | size=128 | time=0.7120s
batch 3 | size=128 | time=0.8003s
batch 4 | size=128 | time=0.8330s
batch 5 | size=128 | time=0.8451s
batch 6 | size=128 | time=0.8730s
batch 7 | size=128 | time=0.8910s
batch 8 | size=128 | time=0.8578s
batch 9 | size=128 | time=0.8951s
batch 10 | size=128 | time=0.9531s
batch 11 | size=128 | time=1.0396s
batch 12 | size=128 | time=1.0951s
batch 13 | size=128 | time=1.0601s
batch 14 | size=128 | time=1.1286s
batch 15 | size=128 | time=1.1062s
batch 16 | size=128 | time=1.1324s
batch 17 | size=128 | time=1.1055s
batch 18 | size=128 | time=1.2069s
batch 19 | size=128 | time=1.2773s
batch 20 | size=128 | time=1.2740s
batch 21 | size=128 | time=1.2484s
batch 22 | size=128 | time=1.2590s
batch 23 | size=128 | time=1.2937s
batch 24 | size=128 | time=1.3250s
batch 25 | size=128 | time=1.3487s
batch 26 | size=128 | time=1.3020s
batch 27 | size=128 | time=1.3694s
batch 28 | size=128 | time=1.4059s
batch 29 | size=128 | time=1.3538s
batch 30 | size=128 | time=1.3629s
batch 31 | size=128 | time=1.3896s
batch 32 | size=128 | time=1.3022s
batch 33 | size=128 | time=1.3949s
batch 34 | size=128 | time=1.3217s
batch 35 | size=128 | time=1.3348s
batch 36 | size=128 | time=1.4937s
batch 37 | size=128 | time=1.5344s
batch 38 | size=128 | time=1.4137s
batch 39 | size=128 | time=1.4401s
batch 40 | size=128 | time=1.4141s
batch 41 | size=128 | time=1.3346s
batch 42 | size=128 | time=1.5419s
batch 43 | size=128 | time=1.6480s
batch 44 | size=128 | time=1.6058s
batch 45 | size=128 | time=1.4574s
batch 46 | size=128 | time=1.5294s
batch 47 | size=128 | time=1.6126s
batch 48 | size=128 | time=1.5886s
batch 49 | size=128 | time=1.6196s
batch 50 | size=128 | time=1.6676s
batch 51 | size=128 | time=1.5862s
batch 52 | size=128 | time=1.7202s
batch 53 | size=128 | time=1.6958s
batch 54 | size=128 | time=1.6409s
batch 55 | size=128 | time=1.6656s
batch 56 | size=128 | time=1.7159s
batch 57 | size=128 | time=1.7495s
batch 58 | size=128 | time=1.7617s
batch 59 | size=128 | time=1.7263s
batch 60 | size=128 | time=1.8117s
batch 61 | size=128 | time=1.7605s
batch 62 | size=128 | time=1.8002s
batch 63 | size=128 | time=1.9555s
batch 64 | size=128 | time=1.7635s
batch 65 | size=128 | time=1.8026s
batch 66 | size=128 | time=1.8645s
batch 67 | size=128 | time=1.9253s
batch 68 | size=128 | time=1.8652s
batch 69 | size=128 | time=2.0552s
batch 70 | size=128 | time=1.9164s
batch 71 | size=128 | time=1.8330s
batch 72 | size=128 | time=1.9929s
batch 73 | size=128 | time=2.0301s
batch 74 | size=128 | time=2.1873s
batch 75 | size=128 | time=2.0505s
batch 76 | size=128 | time=2.2048s
batch 77 | size=128 | time=2.2420s
batch 78 | size=128 | time=2.1440s
batch 79 | size=128 | time=2.1708s
batch 80 | size=128 | time=2.2546s
batch 81 | size=128 | time=2.2686s
batch 82 | size=128 | time=2.2895s
batch 83 | size=128 | time=2.3034s
batch 84 | size=128 | time=2.1511s
batch 85 | size=128 | time=2.4034s
batch 86 | size=128 | time=2.4945s
batch 87 | size=128 | time=2.4349s
batch 88 | size=128 | time=2.2054s
batch 89 | size=128 | time=2.4509s
batch 90 | size=128 | time=2.4427s
batch 91 | size=128 | time=2.4214s
batch 92 | size=128 | time=2.6312s
batch 93 | size=128 | time=2.5481s
batch 94 | size=128 | time=2.2886s
batch 95 | size=128 | time=2.6751s
batch 96 | size=128 | time=2.7953s
batch 97 | size=128 | time=2.4345s
batch 98 | size=128 | time=2.7593s
batch 99 | size=128 | time=2.8534s
batch 100 | size=128 | time=2.7473s
batch 101 | size=128 | time=2.5300s
batch 102 | size=128 | time=2.8541s
batch 103 | size=128 | time=2.7172s
batch 104 | size=128 | time=2.7709s
batch 105 | size=128 | time=2.7380s
batch 106 | size=128 | time=3.2687s
batch 107 | size=128 | time=3.0155s
batch 108 | size=128 | time=3.3043s
batch 109 | size=128 | time=3.2737s
batch 110 | size=128 | time=3.2433s
batch 111 | size=128 | time=3.0358s
batch 112 | size=128 | time=3.0585s
batch 113 | size=128 | time=3.3182s
batch 114 | size=128 | time=3.3782s
batch 115 | size=128 | time=3.6434s
batch 116 | size=128 | time=3.4880s
batch 117 | size=128 | time=3.5901s
batch 118 | size=128 | time=3.7261s
batch 119 | size=128 | time=3.4939s
batch 120 | size=128 | time=3.7634s
batch 121 | size=128 | time=3.7582s
batch 122 | size=128 | time=3.8022s
batch 123 | size=128 | time=4.0355s
batch 124 | size=128 | time=3.9691s
batch 125 | size=128 | time=4.0569s
batch 126 | size=128 | time=4.3412s
batch 127 | size=128 | time=4.4771s
batch 128 | size=128 | time=4.2454s
batch 129 | size=128 | time=4.3850s
batch 130 | size=128 | time=4.3554s
batch 131 | size=128 | time=4.4743s
batch 132 | size=128 | time=4.7560s
batch 133 | size=128 | time=5.0352s
batch 134 | size=128 | time=4.8627s
batch 135 | size=128 | time=5.0502s
batch 136 | size=128 | time=5.5491s
batch 137 | size=128 | time=5.2818s
batch 138 | size=128 | time=5.4890s
batch 139 | size=128 | time=5.7658s
batch 140 | size=128 | time=5.4531s
batch 141 | size=128 | time=5.4034s
batch 142 | size=128 | time=5.9268s
batch 143 | size=128 | time=5.5295s
batch 144 | size=128 | time=5.6457s
batch 145 | size=128 | time=6.3652s
batch 146 | size=128 | time=6.2441s
batch 147 | size=128 | time=6.4925s
batch 148 | size=128 | time=6.3931s
batch 149 | size=128 | time=7.4926s
batch 150 | size=128 | time=7.0570s
batch 151 | size=128 | time=7.1369s
batch 152 | size=128 | time=7.3069s
batch 153 | size=128 | time=7.2254s
batch 154 | size=128 | time=7.4857s
batch 155 | size=128 | time=7.6234s
batch 156 | size=128 | time=8.1041s
batch 157 | size=128 | time=7.9075s
batch 158 | size=128 | time=8.1974s
batch 159 | size=128 | time=8.5397s
batch 160 | size=128 | time=9.2982s
batch 161 | size=128 | time=9.0191s
batch 162 | size=128 | time=9.2791s
batch 163 | size=128 | time=9.6565s
batch 164 | size=128 | time=9.2553s
batch 165 | size=128 | time=10.0323s
batch 166 | size=74 | time=6.4654s

--- summary ---
total embedding time: 521.62s
total docs: 21194
dimension: 1024
Run 3 time: 528.91 sec

============== INDEXING STATS ==============
Documents embedded      : 21194
Runs                    : 3
Individual times        : [521.1580873610001, 528.4577597010002, 528.9112707049999]
Average indexing time   : 526.18 sec
Avg time per document   : 0.024827 sec
Throughput              : 40.28 docs/sec
============================================

In [ ]:
import time
import numpy as np


def measure_dense_retrieval_latency(
    index,
    queries,
    embedding_model,
    top_k=100,
    warmup=True,
    runs=3
):
    """
    Measure end-to-end dense retrieval latency:
    text query -> embedding -> FAISS search
    """

    num_queries = len(queries)

    # Warm-up
    if warmup:
        emb = embedding_model.encode(
            [queries[0]],
            convert_to_numpy=True
        ).astype("float32")

        index.search(emb, top_k)

    times = []

    for _ in tqdm(range(runs)):

        start = time.perf_counter()

        for query in queries:

            # Query embedding
            query_embedding = embedding_model.encode(
                [query],
                convert_to_numpy=True
            ).astype("float32")

            # Retrieval
            index.search(query_embedding, top_k)

        end = time.perf_counter()

        times.append(end - start)


    avg_time = np.mean(times)

    return {
        "num_queries": num_queries,
        "top_k": top_k,
        "runs": runs,
        "total_time_sec": avg_time,
        "avg_latency_per_query_ms": (avg_time / num_queries) * 1000,
        "queries_per_second": num_queries / avg_time,
        "all_runs": times
    }

#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=3
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

100%|██████████| 3/3 [24:28<00:00, 489.38s/it]

============== RETRIEVAL STATS ==============
Total queries           : 5731
Top-k                   : 100
Runs                    : 3
Total time              : 489.37 sec
Avg latency per query   : 85.39 ms
Throughput              : 11.71 queries/sec
============================================

In [ ]:
import os

def get_index_size(index_path):
    """
    Returns FAISS index size in MB/GB.
    """
    size_bytes = os.path.getsize(index_path)

    return {
        "size_bytes": size_bytes,
        "size_MB": size_bytes / (1024 ** 2),
        "size_GB": size_bytes / (1024 ** 3)
    }

index_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/e5-large/sa_faiss.index"

index_size = get_index_size(index_file)

print(f"Index size: {index_size['size_MB']:.2f} MB")
print(f"Index size: {index_size['size_GB']:.3f} GB")

Index size: 87.38 MB
Index size: 0.085 GB

#### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.2358  0.0888     NaN      NaN
1   10  0.2825  0.0588  0.1873   0.2039
2  100  0.4588  0.0107     NaN      NaN

### c. Jina

In [ ]:
!pip install "transformers<5.0.0" "accelerate<1.0.0"

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("jinaai/jina-embeddings-v3", trust_remote_code=True)

In [ ]:
def embed_texts(batch_texts, model):
    """
    BGE-M3 HF embedding (dense only)
    """
    return model.encode(batch_texts)

def build_faiss_pipeline(
    texts,
    ids,
    model,
    batch_size=32,
    save_path=None
):
    all_embeddings = []
    total_time = 0.0

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]

        start = time.time()

        emb = embed_texts(batch, model)

        end = time.time()
        total_time += (end - start)

        print(f"batch {i//batch_size + 1} | size={len(batch)} | time={end-start:.4f}s")

        all_embeddings.append(emb)

    embeddings = np.concatenate(all_embeddings, axis=0).astype("float32")

    dim = np.array(embeddings).shape[1]
    index = faiss.IndexFlatIP(dim)
    index = faiss.IndexIDMap(index)
    index.add_with_ids(embeddings, ids)

    # --- SAVE ARTIFACTS ---
    if save_path:
        os.makedirs(save_path, exist_ok=True)

        # 1. save faiss index
        faiss.write_index(index, os.path.join(save_path, "sa_faiss.index"))

        # 2. save embeddings
        np.save(os.path.join(save_path, "sa_embeddings.npy"), embeddings)

    print("\n--- summary ---")
    print(f"total embedding time: {total_time:.2f}s")
    print(f"total docs: {len(ids)}")
    print(f"dimension: {dim}")

    return index,embeddings

In [ ]:
#embed chunks
# CONFIG
input_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"
output_dir = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/"

BATCH_SIZE = 128

os.makedirs(output_dir, exist_ok=True)

# LOAD DOCUMENTS
data = []

print("Loading documents...")

with open(input_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)

        text = item["article_heading"] + ": " + item["text"]

        data.append({
            "id": item["sub_article_id"],
            "text": text,
            "len": len(text)
        })

# sort for batching efficiency
data.sort(key=lambda x: x["len"])

texts = [d["text"] for d in data]
ids = np.array([d["id"] for d in data], dtype=np.int64)

num_docs = len(texts)

print(f"Total documents: {num_docs}")

# time computation
start_time = time.time()

index, embeddings = build_faiss_pipeline(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path=output_dir
)

end_time = time.time()

# METRICS
total_time = end_time - start_time

avg_time_per_doc = total_time / num_docs
throughput = num_docs / total_time

# REPORT
print("\n================ INDEXING STATS ================")
print(f"Total documents embedded : {num_docs}")
print(f"Total indexing time      : {total_time:.2f} sec")
print(f"Average time per doc     : {avg_time_per_doc:.6f} sec")
print(f"Throughput              : {throughput:.2f} docs/sec")
print("=================================================\n")

In [ ]:
#embed queries
BATCH_SIZE = 128

query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/queries_embed.jsonl"

os.makedirs(os.path.dirname(query_output_file), exist_ok=True)

batch_items = []
batch_texts = []

start_time = time.time()   #

with open(query_output_file, "w", encoding="utf-8") as out_f:
    with open(query_file, "r", encoding="utf-8") as in_f:

        for line in tqdm(in_f, desc="Embedding queries"):

            item = json.loads(line)
            text = item.get("query_text")

            if not text:
                continue

            batch_items.append(item)
            batch_texts.append(text)

            # ---- RUN BATCH ----
            if len(batch_texts) == BATCH_SIZE:

                embeddings = embed_texts(batch_texts, model)

                for it, emb in zip(batch_items, embeddings):
                    to_write = {
                        "query_id": it["query_id"],
                        "query_text": it["query_text"],
                        "embedding": emb.tolist(),
                        "gold": it["relevant_subarticles"]
                    }
                    out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

                batch_items = []
                batch_texts = []

        # ---- FLUSH REMAINING ----
        if batch_texts:
            embeddings = embed_texts(batch_texts, model)

            for it, emb in zip(batch_items, embeddings):
                to_write = {
                    "query_id": it["query_id"],
                    "query_text": it["query_text"],
                    "embedding": emb.tolist(),
                    "gold": it["relevant_subarticles"]
                }
                out_f.write(json.dumps(to_write, ensure_ascii=False) + "\n")

end_time = time.time()   # END TIMER

print("Done! Query embeddings written to:", query_output_file)

# FINAL STATS
total_time = end_time - start_time
print(f"\nTotal embedding time: {total_time:.2f} seconds")
print(f"Average time per query: {total_time / sum(1 for _ in open(query_file)):.4f} sec")

Embedding queries: 5731it [11:31,  8.29it/s]

Done! Query embeddings written to: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/citation_removed_queries_embed.jsonl

Total embedding time: 703.55 seconds
Average time per query: 0.1228 sec

In [ ]:
#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))

query_output_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/queries_embed.jsonl"

all_query_embeddings = []
all_gold_labels = []

print(f"Loading all embeddings from: {query_output_file}")

with open(query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        all_query_embeddings.append(item["embedding"])
        all_gold_labels.append(item["gold"])

# Convert to numpy matrix
query_matrix = np.array(all_query_embeddings).astype("float32")

print(f"Performing batch search for {len(query_matrix)} queries...")

# START TIMER (RETRIEVAL TIME ONLY)
start_time = time.time()

D, I = index.search(query_matrix, 100)

end_time = time.time()

# RETRIEVAL TIME METRICS
retrieval_time = end_time - start_time
num_queries = len(query_matrix)

print("\n================ RETRIEVAL STATS ================")
print(f"Total queries           : {num_queries}")
print(f"Total retrieval time    : {retrieval_time:.4f} sec")
print(f"Avg time per query      : {retrieval_time / num_queries:.6f} sec")
print(f"Throughput             : {num_queries / retrieval_time:.2f} queries/sec")
print("=================================================\n")

# FORMAT RESULTS FOR EVALUATION
all_results_for_metrics = []

for row_idx in range(len(I)):
    retrieved_ids = I[row_idx].tolist()
    all_results_for_metrics.append((retrieved_ids, all_gold_labels[row_idx]))

print("Batch retrieval complete.")

Loading all embeddings from: /content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/queries_embed.jsonl
Performing batch search for 5731 queries...

================ RETRIEVAL STATS ================
Total queries           : 5731
Total retrieval time    : 3.7192 sec
Avg time per query      : 0.000649 sec
Throughput             : 1540.93 queries/sec
=================================================

Batch retrieval complete.

#### Efficiency

In [ ]:
def measure_indexing_time(
    texts,
    ids,
    model,
    batch_size,
    save_path="/content/",
    runs=3
):
    """
    Measure dense indexing time over multiple runs.
    """

    num_docs = len(texts)

    # Warmup
    _ = embed_texts(
        texts[:min(batch_size, num_docs)],
        model
      )

    times = []

    for run in range(runs):
        print(f"\nRunning indexing experiment {run+1}/{runs}...")

        start_time = time.perf_counter()

        index, embeddings = build_faiss_pipeline(
            texts=texts,
            ids=ids,
            model=model,
            batch_size=batch_size,
            save_path=save_path
        )

        end_time = time.perf_counter()

        elapsed = end_time - start_time
        times.append(elapsed)

        print(f"Run {run+1} time: {elapsed:.2f} sec")


    avg_indexing_time = np.mean(times)

    results = {
        "num_documents": num_docs,
        "runs": runs,
        "all_times": times,
        "avg_indexing_time_sec": avg_indexing_time,
        "avg_time_per_document_sec": avg_indexing_time / num_docs,
        "throughput_docs_per_sec": num_docs / avg_indexing_time
    }

    return results

indexing_stats = measure_indexing_time(
    texts=texts,
    ids=ids,
    model=model,
    batch_size=BATCH_SIZE,
    save_path="/content/",
    runs=3
)

print("\n============== INDEXING STATS ==============")
print(f"Documents embedded      : {indexing_stats['num_documents']}")
print(f"Runs                    : {indexing_stats['runs']}")
print(f"Individual times        : {indexing_stats['all_times']}")
print(f"Average indexing time   : {indexing_stats['avg_indexing_time_sec']:.2f} sec")
print(f"Avg time per document   : {indexing_stats['avg_time_per_document_sec']:.6f} sec")
print(f"Throughput              : {indexing_stats['throughput_docs_per_sec']:.2f} docs/sec")
print("============================================")

In [ ]:
import time
import numpy as np


def measure_dense_retrieval_latency(
    index,
    queries,
    embedding_model,
    top_k=100,
    warmup=True,
    runs=3
):
    """
    Measure end-to-end dense retrieval latency:
    text query -> embedding -> FAISS search
    """

    num_queries = len(queries)

    # Warm-up
    if warmup:
        emb = embedding_model.encode(
            [queries[0]],
            convert_to_numpy=True
        ).astype("float32")

        index.search(emb, top_k)

    times = []

    for _ in tqdm(range(runs)):

        start = time.perf_counter()

        for query in queries:

            # Query embedding
            query_embedding = embedding_model.encode(
                [query],
                convert_to_numpy=True
            ).astype("float32")

            # Retrieval
            index.search(query_embedding, top_k)

        end = time.perf_counter()

        times.append(end - start)


    avg_time = np.mean(times)

    return {
        "num_queries": num_queries,
        "top_k": top_k,
        "runs": runs,
        "total_time_sec": avg_time,
        "avg_latency_per_query_ms": (avg_time / num_queries) * 1000,
        "queries_per_second": num_queries / avg_time,
        "all_runs": times
    }

#load and run experiments
index_path="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/"
index = faiss.read_index(os.path.join(index_path, "sa_faiss.index"))
query_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"
query_df=pd.read_json(query_file,lines=True)
batch_texts=query_df['query_text'].tolist()

results=measure_dense_retrieval_latency(
    index=index,
    queries=batch_texts,
    embedding_model=model,
    top_k=100,
    warmup=True,
    runs=1
)

print("\n============== RETRIEVAL STATS ==============")
print(f"Total queries           : {results['num_queries']}")
print(f"Top-k                   : {results['top_k']}")
print(f"Runs                    : {results['runs']}")
print(f"Total time              : {results['total_time_sec']:.2f} sec")
print(f"Avg latency per query   : {results['avg_latency_per_query_ms']:.2f} ms")
print(f"Throughput              : {results['queries_per_second']:.2f} queries/sec")
print("============================================")

100%|██████████| 1/1 [09:18<00:00, 558.45s/it]

============== RETRIEVAL STATS ==============
Total queries           : 5731
Top-k                   : 100
Runs                    : 1
Total time              : 558.45 sec
Avg latency per query   : 97.44 ms
Throughput              : 10.26 queries/sec
============================================

In [ ]:
import os

def get_index_size(index_path):
    """
    Returns FAISS index size in MB/GB.
    """
    size_bytes = os.path.getsize(index_path)

    return {
        "size_bytes": size_bytes,
        "size_MB": size_bytes / (1024 ** 2),
        "size_GB": size_bytes / (1024 ** 3)
    }

index_file = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/sa_faiss.index"

index_size = get_index_size(index_file)

print(f"Index size: {index_size['size_MB']:.2f} MB")
print(f"Index size: {index_size['size_GB']:.3f} GB")

Index size: 87.38 MB
Index size: 0.085 GB

#### Effectiveness

In [ ]:
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions = []
    recalls = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        p = hits / k
        r = hits / len(gold) if len(gold) > 0 else 0.0
        precisions.append(p)
        recalls.append(r)
    avg_p = np.mean(precisions)
    avg_r = np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        ideal_rels = [1] * min(len(gold), k)
        idcg = dcg(ideal_rels)
        rels = [1 if p in gold else 0 for p in preds]
        dcg_val = dcg(rels)
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.2590  0.0964     NaN      NaN
1   10  0.3262  0.0672  0.2024   0.2263
2  100  0.5431  0.0126     NaN      NaN


# 3.Sparse

### a. BM25

In [ ]:
import json
import pickle
import os
import time
import numpy as np
from tqdm import tqdm

In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [ ]:
# 1. IMPORTS + TOKENIZER + STOPWORDS
import json, math, re
from collections import Counter, defaultdict
import numpy as np
import scipy.sparse as sp
try:
    from tqdm.auto import tqdm
except ImportError:
    def tqdm(x, **k): return x

# Devanagari block + word chars, lowercased
TOKEN_RE = re.compile(r"[ऀ-ॣ०-ॿ\w]+", flags=re.UNICODE)
STOPWORDS_PATH = "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/bm25/stopwords_ne.json"

try:
    with open(STOPWORDS_PATH, encoding="utf-8") as f:
        STOPWORDS = frozenset(json.load(f)["stopwords"])
    print(f"Loaded {len(STOPWORDS)} stopwords")
except (FileNotFoundError, TypeError):
    STOPWORDS = frozenset()
    print("No stopwords file found -> running without stopword removal")

def tokenize(text, stopwords=None):
    if stopwords is None:
        stopwords = STOPWORDS
    toks = TOKEN_RE.findall(text.lower())
    if stopwords:
        toks = [t for t in toks if t not in stopwords]
    return toks

Loaded 304 stopwords

In [ ]:
#FAST BM25
# Precompute every BM25 weight ONCE into a sparse (vocab x docs) matrix.
# A query then becomes one sparse matrix-multiply -> scores for all docs.
class FastBM25:
    def __init__(self, k1=1.5, b=0.75, stopwords=frozenset()):
        self.k1, self.b, self.stopwords = k1, b, stopwords
        self.doc_ids = []
        self._vocab = {}
        self._weights = None      # sparse (vocab_size x num_docs)
    def get_index_size(self):
      size_bytes = (
          self._weights.data.nbytes +
          self._weights.indices.nbytes +
          self._weights.indptr.nbytes
      )

      return size_bytes / (1024 ** 2)  # MB

    def build(self, doc_ids, doc_texts):
        self.doc_ids = list(doc_ids)
        raw = defaultdict(list)
        doc_freq = Counter()
        doc_lengths = []
        for text in tqdm(doc_texts, desc="indexing"):
            tc = Counter(tokenize(text, self.stopwords))
            doc_lengths.append(sum(tc.values()))
            doc_idx = len(doc_lengths) - 1
            for term, tf in tc.items():
                raw[term].append((doc_idx, tf))
                doc_freq[term] += 1

        n = len(self.doc_ids)
        dl = np.array(doc_lengths, dtype=np.float32)
        avgdl = float(dl.mean()) if n else 1.0
        norms = self.k1 * (1 - self.b + self.b * dl / (avgdl or 1.0))

        self._vocab = {t: i for i, t in enumerate(raw)}
        rows, cols, data = [], [], []
        for term, postings in raw.items():
            df = doc_freq[term]
            idf = math.log(1 + (n - df + 0.5) / (df + 0.5))
            ids = np.fromiter((p[0] for p in postings), np.int32, len(postings))
            tfs = np.fromiter((p[1] for p in postings), np.float32, len(postings))
            w = idf * (tfs * (self.k1 + 1)) / (tfs + norms[ids])
            rows.append(np.full(len(postings), self._vocab[term], np.int32))
            cols.append(ids)
            data.append(w.astype(np.float32))

        self._weights = sp.csr_matrix(
            (np.concatenate(data), (np.concatenate(rows), np.concatenate(cols))),
            shape=(len(self._vocab), n), dtype=np.float32,
        )
        return self

    def retrieve_batch(self, queries, top_k=100):
        n = len(self.doc_ids)
        if n == 0:
            return [[] for _ in queries]
        limit = min(top_k, n)

        # build a (num_queries x vocab) 0/1 indicator matrix
        q_rows, q_cols = [], []
        for qi, q in enumerate(queries):
            for term in set(tokenize(q, self.stopwords)):
                tid = self._vocab.get(term)
                if tid is not None:
                    q_rows.append(qi)
                    q_cols.append(tid)
        if not q_rows:
            return [[] for _ in queries]

        qm = sp.csr_matrix(
            (np.ones(len(q_rows), np.float32), (q_rows, q_cols)),
            shape=(len(queries), len(self._vocab)), dtype=np.float32,
        )
        scores = (qm @ self._weights).toarray()   # (num_queries x num_docs)

        out = []
        for row in scores:
            idx = np.argpartition(-row, limit - 1)[:limit]
            idx = idx[np.argsort(-row[idx])]
            out.append([(self.doc_ids[int(i)], float(row[i])) for i in idx if row[i] > 0])
        return out

    def retrieve(self, query, top_k=100):
        return self.retrieve_batch([query], top_k)[0]

In [ ]:
#DATA LOADERS  (subarticles corpus + queries with gold)
_SPACE_RE = re.compile(r"\s+")

def _norm(s):
    return _SPACE_RE.sub(" ", s or "").strip()

def load_documents(doc_path):
    """Corpus doc text = 'article_heading: text', id = sub_article_id (kept as-is)."""
    ids, texts, seen = [], [], set()
    with open(doc_path, encoding="utf-8") as f:
        for line in tqdm(f, desc="docs"):
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            did = item["sub_article_id"]
            if did in seen:            # keep first occurrence, like the local pipeline
                continue
            seen.add(did)
            ids.append(did)
            texts.append(_norm(f"{item.get('article_heading', '')}: {item.get('text', '')}"))
    return ids, texts

def load_queries(query_path, query_type="uncited"):
    """Returns (qids, qtexts, golds). gold = relevant_subarticles (list[int]).

    query_type='uncited' removes the raw_citation substring from the query text so
    the answer isn't leaked; 'cited' leaves the query untouched.
    """
    qids, qtexts, golds = [], [], []
    with open(query_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            text = _norm(str(item.get("query_text", "")))
            gold = item.get("relevant_subarticles") or []
            if text and gold:          # skip queries with no text or no gold
                qids.append(str(item.get("query_id", "")))
                qtexts.append(text)
                golds.append(list(gold))
    return qids, qtexts, golds

In [ ]:
import time

# CONFIG
DOC_PATH   = "/content/drive/MyDrive/LegalNLPBenchmark Data/documents/chunks/subarticles.jsonl"

# INDEXING
doc_ids, doc_texts = load_documents(DOC_PATH)
print(f"{len(doc_ids)} documents")

start_index = time.time()

bm25 = FastBM25(stopwords=STOPWORDS).build(
    doc_ids,
    doc_texts
)

end_index = time.time()

indexing_time = end_index - start_index

print("\n========== INDEXING ==========")
print(f"Documents           : {len(doc_ids)}")
print(f"Indexing time       : {indexing_time:.4f} sec")
print(f"Avg/doc             : {indexing_time/len(doc_ids):.6f} sec")
print(f"Docs/sec            : {len(doc_ids)/indexing_time:.2f}")
print("================================\n")

In [ ]:
bm25.get_index_size()

6.003780364990234

In [ ]:
import time

TOP_K      = 100

all_query_results = {}


QUERY_PATH = f"/content/drive/MyDrive/LegalNLPBenchmark Data/queries/single-hop/queries.jsonl"


# LOAD QUERIES
qids, qtexts, golds = load_queries(QUERY_PATH)

print(f"Queries: {len(qids)}")


# RETRIEVAL
start_retrieval = time.time()

retrieved = bm25.retrieve_batch(
    qtexts,
    top_k=TOP_K
)

end_retrieval = time.time()

retrieval_time = end_retrieval - start_retrieval


print(f"Retrieval time: {retrieval_time:.4f} sec")
print(f"Avg/query: {retrieval_time/len(qids):.6f} sec")


# FORMAT FOR EVALUATION
all_results_for_metrics = [
    (
        [doc_id for doc_id, _score in preds],
        gold
    )
    for preds, gold in zip(retrieved, golds)
]

print("\nFinished all query spans")

Queries: 5731
Retrieval time: 13.6126 sec
Avg/query: 0.002375 sec

Finished all query spans

In [ ]:
#METRICS
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions, recalls = [], []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        precisions.append(hits / k)
        recalls.append(hits / len(gold) if len(gold) > 0 else 0.0)
    avg_p, avg_r = np.mean(precisions), np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        idcg = dcg([1] * min(len(gold), k))
        dcg_val = dcg([1 if p in gold else 0 for p in preds])
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

In [ ]:

# Define K values for Recall only
ks = [5, 10,100]

eval_results = []

if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:

    # Compute fixed metrics once (K=10)
    mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
    ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

    for k in ks:
        rec = recall_at_k(all_results_for_metrics, k=k)
        f1 = f1_at_k(all_results_for_metrics, k=k)

        eval_results.append({
            "K": k,
            "Recall": round(rec, 4),
            "F1": round(f1, 4),

            # only filled at K=10, else blank/None
            "MRR@10": round(mrr_10, 4) if k == 10 else None,
            "NDCG@10": round(ndcg_10, 4) if k == 10 else None
        })

    df_metrics = pd.DataFrame(eval_results)
    display(df_metrics)

else:
    print("Error: 'all_results_for_metrics' not found. Please run the retrieval cell first.")

     K  Recall      F1  MRR@10  NDCG@10
0    5  0.3593  0.1284     NaN      NaN
1   10  0.4166  0.0824  0.2972   0.3203
2  100  0.5996  0.0134     NaN      NaN

# 4.Hybrid Model

### a.Bm25&bge

In [ ]:
!pip install faiss-cpu

In [ ]:
import faiss
import json
import numpy as np
from tqdm import tqdm

In [ ]:
def min_max_normalize(results):
    """
    results: [(doc_id, score), ...]
    """
    if not results:
        return {}

    scores = [score for _, score in results]
    min_score = min(scores)
    max_score = max(scores)

    if max_score == min_score:
        return {doc_id: 1.0 for doc_id, _ in results}

    return {
        doc_id: (score - min_score) / (max_score - min_score)
        for doc_id, score in results
    }


def score_fusion(bm25_candidates, bge_candidates, alpha=0.5):
    """
    alpha:
        1.0 -> only BM25
        0.0 -> only BGE
        0.5 -> equal weighting
    """

    bm25_norm = min_max_normalize(bm25_candidates)
    bge_norm = min_max_normalize(bge_candidates)

    fused_scores = {}

    # BM25 contribution
    for doc_id, score in bm25_norm.items():
        fused_scores[doc_id] = alpha * score

    # BGE contribution
    for doc_id, score in bge_norm.items():
        fused_scores[doc_id] = fused_scores.get(doc_id, 0) + (1-alpha) * score

    # Rank documents
    ranked = sorted(
        fused_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return ranked

In [ ]:
### jina query import
jina_embeddings=[]
texts=[]
golds=[]
jina_query_output_file="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/queries_embed.jsonl"
with open(jina_query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        texts.append(item["query_text"])
        jina_embeddings.append(item["embedding"])
        golds.append(item["gold"])

# Load BGE FAISS index
jina_index = faiss.read_index(
    "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/jina-v3/sa_faiss.index"
)

In [ ]:
# Load jina query embeddings
jina_embeddings = np.asarray(
    jina_embeddings,
    dtype=np.float32
)

TOP_K = 100

hybrid_candidates = []

# Retrieve candidates
for i, query in enumerate(tqdm(texts, desc="Hybrid retrieval")):
    # BM25
    bm_candidates = bm25.retrieve(query, TOP_K)

    # BGE
    D, I = jina_index.search(
        jina_embeddings[i:i+1],
        TOP_K
    )
    bge_candidates = list(zip(I[0].tolist(), D[0].tolist()))
    hybrid_candidates.append(
        {
            "query": query,
            "bm25": bm_candidates,
            "jina": bge_candidates,
            "gold": golds[i]
        }
    )

Hybrid retrieval: 100%|██████████| 5731/5731 [02:40<00:00, 35.76it/s]

#### Effectiveness

In [ ]:
#METRICS
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions, recalls = [], []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        precisions.append(hits / k)
        recalls.append(hits / len(gold) if len(gold) > 0 else 0.0)
    avg_p, avg_r = np.mean(precisions), np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        idcg = dcg([1] * min(len(gold), k))
        dcg_val = dcg([1 if p in gold else 0 for p in preds])
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

# # only evaluate at cutoffs we actually retrieved
# ks = [k for k in [5, 10, 100] if k <= TOP_K]

# if 'all_results_for_metrics' in globals() and len(all_results_for_metrics) > 0:
#     mrr_10 = mrr_at_k(all_results_for_metrics, k=10)
#     ndcg_10 = ndcg_at_k(all_results_for_metrics, k=10)

#     eval_results = []
#     for k in ks:
#         eval_results.append({
#             "K": k,
#             "Recall": round(recall_at_k(all_results_for_metrics, k=k), 4),
#             "F1": round(f1_at_k(all_results_for_metrics, k=k), 4),
#             "MRR@10": round(mrr_10, 4) if k == 10 else None,
#             "NDCG@10": round(ndcg_10, 4) if k == 10 else None,
#         })
#     df_metrics = pd.DataFrame(eval_results)
#     display(df_metrics)
# else:
#     print("Error: 'all_results_for_metrics' not found. Run the retrieval cell (5) first.")

In [ ]:
import pandas as pd

alpha_results = []

for alpha in [round(i * 0.1, 1) for i in range(1, 10)]:
    all_results_for_metrics = []

    for item in hybrid_candidates:
        fused_candidates = score_fusion(
            item["bm25"],
            item["jina"],
            alpha=alpha
        )

        all_results_for_metrics.append(
            (
                [doc_id for doc_id, _score in fused_candidates],
                item["gold"]
            )
        )

    # Recall
    alpha_results.append({
        "alpha": alpha,
        "Recall@5": round(recall_at_k(all_results_for_metrics, k=5), 4),
        "Recall@10": round(recall_at_k(all_results_for_metrics, k=10), 4),
        "Recall@100": round(recall_at_k(all_results_for_metrics, k=100), 4),
        "MRR@10": round(mrr_at_k(all_results_for_metrics, k=10), 4),
        "NDCG@10": round(ndcg_at_k(all_results_for_metrics, k=10), 4),
    })

df_alpha_recall = pd.DataFrame(alpha_results)

display(df_alpha_recall)

   alpha  Recall@5  Recall@10  Recall@100  MRR@10  NDCG@10
0    0.1    0.2794     0.3437      0.6237  0.2190   0.2432
1    0.2    0.3032     0.3633      0.6312  0.2402   0.2642
2    0.3    0.3248     0.3946      0.6346  0.2613   0.2877
3    0.4    0.3587     0.4323      0.6388  0.2832   0.3131
4    0.5    0.3875     0.4509      0.6409  0.3128   0.3396
5    0.6    0.3914     0.4529      0.6420  0.3171   0.3437
6    0.7    0.3869     0.4476      0.6427  0.3144   0.3406
7    0.8    0.3763     0.4409      0.6420  0.3083   0.3343
8    0.9    0.3653     0.4304      0.6401  0.3010   0.3262

### b.Bm25&acostillio

In [ ]:
def min_max_normalize(results):
    """
    results: [(doc_id, score), ...]
    """
    if not results:
        return {}

    scores = [score for _, score in results]
    min_score = min(scores)
    max_score = max(scores)

    if max_score == min_score:
        return {doc_id: 1.0 for doc_id, _ in results}

    return {
        doc_id: (score - min_score) / (max_score - min_score)
        for doc_id, score in results
    }


def score_fusion(bm25_candidates, bge_candidates, alpha=0.5):
    """
    alpha:
        1.0 -> only BM25
        0.0 -> only BGE
        0.5 -> equal weighting
    """

    bm25_norm = min_max_normalize(bm25_candidates)
    bge_norm = min_max_normalize(bge_candidates)

    fused_scores = {}

    # BM25 contribution
    for doc_id, score in bm25_norm.items():
        fused_scores[doc_id] = alpha * score

    # BGE contribution
    for doc_id, score in bge_norm.items():
        fused_scores[doc_id] = fused_scores.get(doc_id, 0) + (1-alpha) * score

    # Rank documents
    ranked = sorted(
        fused_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return ranked

In [ ]:
### bge query import
acos_embeddings=[]
texts=[]
golds=[]
ascos_query_output_file="/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/queries_embed.jsonl"
with open(ascos_query_output_file, "r", encoding="utf-8") as f:
    for line in f:
        item = json.loads(line)
        texts.append(item["query_text"])
        acos_embeddings.append(item["embedding"])
        golds.append(item["gold"])

# Load BGE FAISS index
acos_index = faiss.read_index(
    "/content/drive/MyDrive/LegalNLPBenchmark Data/experiments/retrieval/acost-nepali/sa_faiss.index"
)

In [ ]:
# Load BGE query embeddings
acos_embeddings = np.asarray(
    acos_embeddings,
    dtype=np.float32
)

TOP_K = 100

hybrid_candidates = []

# Retrieve candidates
for i, query in enumerate(tqdm(texts, desc="Hybrid retrieval")):
    # BM25
    bm_candidates = bm25.retrieve(query, TOP_K)

    # BGE
    D, I = acos_index.search(
        acos_embeddings[i:i+1],
        TOP_K
    )
    acos_candidates = list(zip(I[0].tolist(), D[0].tolist()))
    hybrid_candidates.append(
        {
            "query": query,
            "bm25": bm_candidates,
            "acos": acos_candidates,
            "gold": golds[i]
        }
    )

Hybrid retrieval: 100%|██████████| 5731/5731 [02:16<00:00, 41.96it/s]

In [ ]:
#METRICS
import numpy as np
import ast
import pandas as pd

def parse_gold(gold):
    if isinstance(gold, str):
        return list(map(int, ast.literal_eval(gold)))
    return gold

def mrr_at_k(results, k):
    rr_sum = 0.0
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        rr = 0.0
        for rank, pid in enumerate(preds, start=1):
            if pid in gold:
                rr = 1.0 / rank
                break
        rr_sum += rr
    return rr_sum / len(results)

def f1_at_k(results, k):
    precisions, recalls = [], []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        hits = len(set(preds).intersection(gold))
        precisions.append(hits / k)
        recalls.append(hits / len(gold) if len(gold) > 0 else 0.0)
    avg_p, avg_r = np.mean(precisions), np.mean(recalls)
    return 2 * avg_p * avg_r / (avg_p + avg_r) if (avg_p + avg_r) > 0 else 0.0

def recall_at_k(results, k=10):
    recalls = []

    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]

        if len(gold) == 0:
            recalls.append(0.0)
            continue

        hits = len(set(preds).intersection(gold))
        recalls.append(hits / len(gold))

    return np.mean(recalls)

def dcg(rels):
    return sum(rel / np.log2(i + 2) for i, rel in enumerate(rels))

def ndcg_at_k(results, k):
    scores = []
    for preds, gold in results:
        gold = set(parse_gold(gold))
        preds = preds[:k]
        idcg = dcg([1] * min(len(gold), k))
        dcg_val = dcg([1 if p in gold else 0 for p in preds])
        scores.append(dcg_val / idcg if idcg > 0 else 0.0)
    return np.mean(scores)

In [ ]:
import pandas as pd

alpha_results = []

for alpha in [round(i * 0.1, 1) for i in range(1, 10)]:
    all_results_for_metrics = []

    for item in hybrid_candidates:
        fused_candidates = score_fusion(
            item["bm25"],
            item["acos"],
            alpha=alpha
        )

        all_results_for_metrics.append(
            (
                [doc_id for doc_id, _score in fused_candidates],
                item["gold"]
            )
        )

    # Recall
    alpha_results.append({
        "alpha": alpha,
        "Recall@5": round(recall_at_k(all_results_for_metrics, k=5), 4),
        "Recall@10": round(recall_at_k(all_results_for_metrics, k=10), 4),
        "Recall@100": round(recall_at_k(all_results_for_metrics, k=100), 4),
        "MRR@10": round(mrr_at_k(all_results_for_metrics, k=10), 4),
        "NDCG@10": round(ndcg_at_k(all_results_for_metrics, k=10), 4),
    })

df_alpha_recall = pd.DataFrame(alpha_results)

display(df_alpha_recall)

   alpha  Recall@5  Recall@10  Recall@100  MRR@10  NDCG@10
0    0.1    0.2634     0.3272      0.6434  0.1993   0.2253
1    0.2    0.2859     0.3508      0.6512  0.2239   0.2492
2    0.3    0.3102     0.3760      0.6582  0.2494   0.2740
3    0.4    0.3426     0.4135      0.6625  0.2760   0.3024
4    0.5    0.3782     0.4391      0.6644  0.3080   0.3331
5    0.6    0.3837     0.4426      0.6638  0.3155   0.3398
6    0.7    0.3800     0.4403      0.6628  0.3138   0.3382
7    0.8    0.3728     0.4345      0.6592  0.3076   0.3320
8    0.9    0.3667     0.4279      0.6516  0.3019   0.3262